In [ ]:
import numpy as np
import pandas
import math
from sklearn.utils import shuffle
from matplotlib import pyplot
from sklearn.metrics import accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pandas.read_csv("diabetes.csv")
#data=data.drop(columns=["Unnamed: 0"])
df=data

In [ ]:
import numpy as np

def standardize(data):
    """
    Standardize the input data to have mean 0 and standard deviation 1.

    Parameters:
    data (numpy.ndarray): Input data as a NumPy array.

    Returns:
    numpy.ndarray: Standardized data.
    """
    mean = np.mean(data)
    std_dev = np.std(data)
    standardized_data = (data - mean) / std_dev
    return standardized_data

# Example usage
height1 = standardize(data['Height'])
weight1 = standardize(data['Weight'])
print("Original data:", data)


Original data:      Height  Weight  Index
0       161      89      4
1       179     127      4
2       172     139      5
3       153     104      5
4       165      68      2
..      ...     ...    ...
395     166     160      5
396     145     130      5
397     178     138      5
398     168     158      5
399     161     155      5

[400 rows x 3 columns]


In [ ]:
data.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [ ]:
data["Weight"]=weight1
data["Height"]=height1

In [ ]:
data

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0            0              0                   1           0       0   
1            0              0                   1           0       0   
2            0              0                   0           0       0   
3            0              0                   0           0       0   
4            0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [ ]:
print(weight1)

0     -0.527818
1      0.647861
2      1.019128
3     -0.063734
4     -1.177535
         ...   
395    1.668845
396    0.740677
397    0.988189
398    1.606967
399    1.514150
Name: Weight, Length: 400, dtype: float64


In [ ]:
Income,CCAvg,Mortgage

In [ ]:
dummies = pandas.get_dummies(data['Index'])
print(dummies)
res=[]
for i in range(len(dummies)):
    samp=[]
    ele=[]

    ele.append(dummies[0][i])
    ele.append(dummies[1][i])
    ele.append(dummies[2][i])
    ele.append(dummies[3][i])
    ele.append(dummies[4][i])
    ele.append(dummies[5][i])
    samp.append(ele)
    res.append(samp)
dl=pandas.DataFrame(res,columns=['Index'])
data=data.drop(columns=['Index'],axis=1)
data = pandas.concat([data, dl], axis=1)

     0  1  2  3  4  5
0    0  0  0  0  1  0
1    0  0  0  0  1  0
2    0  0  0  0  0  1
3    0  0  0  0  0  1
4    0  0  1  0  0  0
..  .. .. .. .. .. ..
395  0  0  0  0  0  1
396  0  0  0  0  0  1
397  0  0  0  0  0  1
398  0  0  0  0  0  1
399  0  0  0  0  0  1

[400 rows x 6 columns]


In [ ]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age Outcome  
0                       0.627   50  [0, 1]  
1                       0.351   31  [1, 0]  
2                       0.672   32  [0, 1]  
3                       0.167   21  [1, 0]  
4                       2.288   33  [0, 1]  
..                        ...  ...     ...  
763                     0.171   63  [1, 0]  
764                     0.340   27  [1, 0]  
765                     0.245   30  [1, 0]  
766                     0.349   47  [0, 1]  
767                     0.315   23  [1, 0]  

[768 rows x 9 columns]

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Sample data with 9 features and class labels
np.random.seed(0)
num_samples = 100
num_features = 9
#data = np.random.rand(num_samples, num_features)
labels = np.random.randint(0, 3, size=num_samples)

# Choose two features to plot (you can change these as needed)
feature1 = data[:, 0]
feature2 = data[:, 1]

class0 = data[labels == 0]
class1 = data[labels == 1]
class2 = data[labels == 2]

# Create a scatter plot
plt.scatter(class0[:, 0], class0[:, 1], c='b', label='Class 0', marker='o')
plt.scatter(class1[:, 0], class1[:, 1], c='r', label='Class 1', marker='x')
plt.scatter(class2[:, 0], class2[:, 1], c='g', label='Class 2', marker='s')

plt.xlabel(f'Feature 0')
plt.ylabel(f'Feature 1')
plt.legend(loc='best')

plt.show()


In [ ]:
dummies = pandas.get_dummies(data['CreditCard'])
res=[]
for i in range(len(dummies)):
    samp=[]
    ele=[]

    ele.append(dummies[0][i])
    ele.append(dummies[1][i])

    samp.append(ele)
    res.append(samp)
dl=pandas.DataFrame(res,columns=['CreditCard'])
data=data.drop(columns=['CreditCard'],axis=1)
data = pandas.concat([data, dl], axis=1)

In [ ]:
dummies = pandas.get_dummies(data['Outcome'])
res=[]
for i in range(len(dummies)):
    samp=[]
    ele=[]

    ele.append(dummies[0][i])
    ele.append(dummies[1][i])

    samp.append(ele)
    res.append(samp)
dl=pandas.DataFrame(res,columns=['Outcome'])
data=data.drop(columns=['Outcome'],axis=1)
data = pandas.concat([data, dl], axis=1)

In [ ]:
data=data.drop(columns=['ID','ZIP Code'],axis=1)

In [ ]:
data=data.drop(columns=['Gender'],axis=1)

KeyError: "['Gender'] not found in axis"

In [ ]:
data = data.sample(frac=1)

data

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
17      0.936914 -0.434859       0.253036      -1.288212 -0.692891 -0.303664   
148     0.342981  0.817027       0.459827      -1.288212 -0.692891  0.216705   
177    -1.141852  0.253678       2.114155       1.597279  0.435886  4.455807   
14      0.342981  1.411672       0.149641      -0.096379  0.826616 -0.785957   
22      0.936914  2.350587       1.080200      -1.288212 -0.692891  0.990912   
..           ...       ...            ...            ...       ...       ...   
64      0.936914 -0.215779      -0.160546      -1.288212 -0.692891  0.102477   
197    -0.250952 -0.434859      -0.367337      -0.472747 -0.276112 -1.154023   
8      -0.547919  2.381884       0.046245       1.534551  4.021922 -0.189437   
27     -0.844885 -0.747831      -0.160546      -0.347291  0.522715 -1.115947   
39      0.046014 -0.309671       0.149641       1.660007  1.104469  0.648230   

     DiabetesPedigreeFunction       Age Outcome  
17                  -0.658012 -0.190672  [0, 1]  
148                 -0.766737  2.702312  [1, 0]  
177                 -0.461705 -0.616111  [0, 1]  
14                   0.347687  1.511083  [0, 1]  
22                  -0.063049  0.660206  [0, 1]  
..                        ...       ...     ...  
64                  -0.645932  0.745293  [0, 1]  
197                  0.622518 -0.871374  [0, 1]  
8                   -0.947944  1.681259  [0, 1]  
27                   0.045675 -0.956462  [1, 0]  
39                   2.772843  1.936522  [0, 1]  

[200 rows x 9 columns]

In [ ]:
c=data.columns.values
print(c)

['Pregnancies' 'Glucose' 'BloodPressure' 'SkinThickness' 'Insulin' 'BMI'
 'DiabetesPedigreeFunction' 'Age' 'Outcome']


In [ ]:
import numpy as np

def standardize(data):
    """
    Standardize the input data to have mean 0 and standard deviation 1.

    Parameters:
    data (numpy.ndarray): Input data as a NumPy array.

    Returns:
    numpy.ndarray: Standardized data.
    """
    mean = np.mean(data)
    std_dev = np.std(data)
    standardized_data = (data - mean) / std_dev
    return standardized_data

# Example usage

print("Original data:", data)


Original data:      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age Outcome  
0                       0.627   50  [0, 1]  
1     

In [ ]:
list(c)
for i in range(len(c)):
    print(data[c[i]])
    data[c[i]]=standardize(data[c[i]])

0       6
1       1
2       8
3       1
4       0
       ..
763    10
764     2
765     5
766     1
767     1
Name: Pregnancies, Length: 768, dtype: int64
0      148
1       85
2      183
3       89
4      137
      ... 
763    101
764    122
765    121
766    126
767     93
Name: Glucose, Length: 768, dtype: int64
0      72
1      66
2      64
3      66
4      40
       ..
763    76
764    70
765    72
766    60
767    70
Name: BloodPressure, Length: 768, dtype: int64
0      35
1      29
2       0
3      23
4      35
       ..
763    48
764    27
765    23
766     0
767    31
Name: SkinThickness, Length: 768, dtype: int64
0        0
1        0
2        0
3       94
4      168
      ... 
763    180
764      0
765    112
766      0
767      0
Name: Insulin, Length: 768, dtype: int64
0      33.6
1      26.6
2      23.3
3      28.1
4      43.1
       ... 
763    32.9
764    36.8
765    26.2
766    30.1
767    30.4
Name: BMI, Length: 768, dtype: float64
0      0.627
1      0.351
2      0.6

TypeError: float() argument must be a string or a number, not 'list'

In [ ]:
data=data.iloc[:200,:]
print(data)

     Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.639947  0.848324       0.149641       0.907270 -0.692891  0.204013   
1      -0.844885 -1.123396      -0.160546       0.530902 -0.692891 -0.684422   
2       1.233880  1.943724      -0.263941      -1.288212 -0.692891 -1.103255   
3      -0.844885 -0.998208      -0.160546       0.154533  0.123302 -0.494043   
4      -1.141852  0.504055      -1.504687       0.907270  0.765836  1.409746   
..           ...       ...            ...            ...       ...       ...   
195     0.342981  1.161295       0.770014       1.283638  1.130518  0.940144   
196    -0.844885 -0.497453      -0.574128      -1.288212 -0.692891 -0.976336   
197    -0.250952 -0.434859      -0.367337      -0.472747 -0.276112 -1.154023   
198     0.046014 -0.372265      -0.263941       1.471822  0.166716  0.356316   
199     0.046014  0.848324      -0.470732       0.405445  2.068270 -0.138669   

     DiabetesPedigreeFunction       Age

In [ ]:

def remove_outliers(df, column_name, threshold=1.5):
    Q1 = df[column_name].quantile(0.25)
    Q3 = df[column_name].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - threshold * IQR
    upper_bound = Q3 + threshold * IQR
    return df[(df[column_name] >= lower_bound) & (df[column_name] <= upper_bound)]

# Remove outliers from column 'A' with a threshold of 1.5
data= remove_outliers(data, 'Mortgage', threshold=1.5)

print(data)


KeyError: 'Mortgage'

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Sample data with class labels

# Extract features and class labels
X = data.iloc[:, :-1]  # Features
labels = data.iloc[:, -1]  # Class labels

# Separate data by class labels
class0 = X[labels == 0]
class1 = X[labels == 1]
print(X)
print(labels)
print("class 0:",class0)
print("class 1:",class1)
# Create a scatter plot
plt.scatter(class0[:, 0], class0[:, 1], c='b', label='Class 0', marker='o')
plt.scatter(class1[:, 0], class1[:, 1], c='r', label='Class 1', marker='x')

# Add labels and legend
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.legend(loc='best')

# Show the plot
plt.show()


      Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
0      25           1      49       4    1.6          1         0   
1      45          19      34       3    1.5          1         0   
2      39          15      11       1    1.0          1         0   
3      35           9     100       1    2.7          2         0   
4      35           8      45       4    1.0          2         0   
...   ...         ...     ...     ...    ...        ...       ...   
4995   29           3      40       1    1.9          3         0   
4996   30           4      15       4    0.4          1        85   
4997   63          39      24       2    0.3          3         0   
4998   65          40      49       3    0.5          2         0   
4999   28           4      83       3    0.8          1         0   

      Personal Loan  Securities Account  CD Account  Online  
0                 0                   1           0       0  
1                 0                   1        

TypeError: '(slice(None, None, None), 0)' is an invalid key

In [ ]:
class Perceptron:
    def __init__(self, no_features, eta):
        self.no_features = no_features
        self.eta = eta
        self.wts = numpy.zeros(1 + self.no_features)
    def sigmoid(x):
    return 1 / (1 + math.exp(-x))

    def activation(self, v):
        result = sigmoid(v)
        return result

    def prepend_bias(self, x):
        return numpy.insert(x, 0, 1)

    def wixi(self, X):
        xi_bias = self.prepend_bias(X)
        v = self.wts.T.dot(xi_bias)# W^T *x
        return v

    def train(self, X):
        for xi in X:
            v = self.wixi(xi)
            y = self.activation(v)


IndentationError: expected an indented block (<ipython-input-9-68b3d6626baf>, line 7)

In [ ]:
class Hidden_layer_perceptron:

    def __init__(self, no_features, eta):
       # self.no_classes = no_classes
        self.perceptrons = []
        for i in range(no_features):
            percep=Perceptron(no_features, eta)
            self.perceptrons.append(percep)
        self.hidden=[]


    def train(self, X, D, epochs: int = 1):
        for _ in range(epochs):
            for i in range(self.no_features):
                self.perceptrons[i].train(X)

    def predict(self, x):
        return [percep.predict(x) for percep in self.perceptrons]

    def test(self, X):
        Y_pred = []
        for xi in X:
            y = self.predict(xi)
            Y_pred.append(y)
        return numpy.array(Y_pred)

In [ ]:
ETA=1

In [ ]:
a=np.ones(5)

In [ ]:
a

array([1., 1., 1., 1., 1.])

In [ ]:
data

Age  Experience    Income    Family     CCAvg  Education  Mortgage  \
0    -1.774417   -1.666078 -0.538229  1.397414 -0.193385  -1.049078 -0.555524   
1    -0.029524   -0.096330 -0.864109  0.525991 -0.250611  -1.049078 -0.555524   
2    -0.552992   -0.445163 -1.363793 -1.216855 -0.536736  -1.049078 -0.555524   
3    -0.901970   -0.968413  0.569765 -1.216855  0.436091   0.141703 -0.555524   
4    -0.901970   -1.055621 -0.625130  1.397414 -0.536736   0.141703 -0.555524   
...        ...         ...       ...       ...       ...        ...       ...   
4995 -1.425438   -1.491662 -0.733757 -1.216855 -0.021710   1.332484 -0.555524   
4996 -1.338194   -1.404454 -1.276892  1.397414 -0.880087  -1.049078  0.280238   
4997  1.540880    1.647835 -1.081363 -0.345432 -0.937312   1.332484 -0.555524   
4998  1.715370    1.735043 -0.538229  0.525991 -0.822862   0.141703 -0.555524   
4999 -1.512683   -1.404454  0.200434  0.525991 -0.651186  -1.049078 -0.555524   

      Personal Loan  Securities Account  CD Account    Online CreditCard  
0         -0.325875            2.928915    -0.25354 -1.216618     [1, 0]  
1         -0.325875            2.928915    -0.25354 -1.216618     [1, 0]  
2         -0.325875           -0.341423    -0.25354 -1.216618     [1, 0]  
3         -0.325875           -0.341423    -0.25354 -1.216618     [1, 0]  
4         -0.325875           -0.341423    -0.25354 -1.216618     [0, 1]  
...             ...                 ...         ...       ...        ...  
4995      -0.325875           -0.341423    -0.25354  0.821951     [1, 0]  
4996      -0.325875           -0.341423    -0.25354  0.821951     [1, 0]  
4997      -0.325875           -0.341423    -0.25354 -1.216618     [1, 0]  
4998      -0.325875           -0.341423    -0.25354  0.821951     [1, 0]  
4999      -0.325875           -0.341423    -0.25354  0.821951     [0, 1]  

[5000 rows x 12 columns]

In [ ]:
train_X

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
555    34           8      35       4    0.8          1       137   
222    26           2     104       3    2.5          1         0   
2984   54          28      94       2    1.1          1       188   
4218   52          27      43       4    0.2          2         0   
3213   39           9      32       3    2.0          3       116   
...   ...         ...     ...     ...    ...        ...       ...   
641    35          10     139       2    7.8          1         0   
4235   27           1      91       2    0.2          1         0   
905    46          22      28       1    1.0          1        84   
2469   43          18      89       1    0.1          2       307   
169    27           1     112       4    2.1          3         0   

      Personal Loan  Securities Account  CD Account  Online  
555               0                   0           1       1  
222               0                   0           0       0  
2984              0                   0           0       0  
4218              0                   0           0       0  
3213              0                   0           0       1  
...             ...                 ...         ...     ...  
641               0                   0           0       0  
4235              0                   0           0       1  
905               0                   0           0       1  
2469              0                   0           0       0  
169               0                   0           0       0  

[5000 rows x 11 columns]

In [ ]:
data

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
257    258   66          41      18     92691       3    0.5          1   
1550  1551   40          14      39     93117       1    2.0          1   
4203  4204   59          33      88     93106       4    1.9          2   
3724  3725   44          20      39     93108       2    2.1          3   
513    514   30           6      48     94607       1    2.1          3   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4554  4555   41          16     109     94801       3    1.0          1   
3403  3404   54          29      82     94709       3    3.7          2   
3277  3278   43          19      81     92121       2    3.2          1   
3880  3881   48          24      25     90024       4    0.5          2   
1642  1643   27           3      84     95814       3    1.5          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
257          0              0                   0           0       0   
1550         0              0                   0           0       1   
4203         0              0                   0           0       0   
3724       119              0                   0           0       0   
513          0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4554         0              0                   1           0       1   
3403         0              1                   0           0       1   
3277         0              0                   0           0       1   
3880         0              0                   0           0       0   
1642         0              0                   0           0       1   

     CreditCard  
257      [0, 1]  
1550     [1, 0]  
4203     [1, 0]  
3724     [1, 0]  
513      [1, 0]  
...         ...  
4554     [1, 0]  
3403     [1, 0]  
3277     [1, 0]  
3880     [1, 0]  
1642     [0, 1]  

[150 rows x 14 columns]

In [ ]:
a=data.iloc[:,-1]

In [ ]:
a=a.to_numpy()

In [ ]:
a[10][0]

0

In [ ]:
a

array([list([0, 1]), list([1, 0]), list([1, 0]), list([1, 0]),
       list([1, 0]), list([1, 0]), list([1, 0]), list([1, 0]),
       list([1, 0]), list([1, 0]), list([0, 1]), list([1, 0]),
       list([1, 0]), list([1, 0]), list([1, 0]), list([1, 0]),
       list([1, 0]), list([1, 0]), list([1, 0]), list([1, 0]),
       list([1, 0]), list([1, 0]), list([1, 0]), list([0, 1]),
       list([0, 1]), list([1, 0]), list([0, 1]), list([1, 0]),
       list([1, 0]), list([1, 0]), list([0, 1]), list([1, 0]),
       list([1, 0]), list([0, 1]), list([1, 0]), list([0, 1]),
       list([0, 1]), list([0, 1]), list([1, 0]), list([1, 0]),
       list([1, 0]), list([0, 1]), list([0, 1]), list([1, 0]),
       list([0, 1]), list([1, 0]), list([0, 1]), list([0, 1]),
       list([0, 1]), list([1, 0]), list([1, 0]), list([0, 1]),
       list([0, 1]), list([1, 0]), list([0, 1]), list([1, 0]),
       list([1, 0]), list([0, 1]), list([0, 1]), list([1, 0]),
       list([1, 0]), list([1, 0]), list([1, 0]), list([

In [ ]:
import pandas as pd

# Load your dataset
#df = pd.read_csv('your_dataset.csv')

# Create a boxplot for each column
plt.figure(figsize=(12, 6))
df.boxplot(whis=1.5)  # Adjust the whisker length (whis) as needed
plt.title('Boxplot of Columns')
plt.show()

# Identify outliers using the boxplot
q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr = q3 - q1
outliers = ((df < (q1 - 1.5 * iqr)) | (df > (q3 + 1.5 * iqr)))

# Remove outliers from the DataFrame
df_no_outliers = df[~outliers.any(axis=1)]

# Display the DataFrame without outliers
print(df_no_outliers)


In [ ]:
def threshold(xi):
    output=[]
    xi=xi.ravel()
    print(xi)
    for i in xi:
        if(i>=0.5):
            output.append(1)
        else:
            output.append(0)
    return(output)
def op(xi):
    xi=xi.ravel()
    print("length:",len(xi.ravel()))
    ix= np.argmax(xi)
    print("xi:",xi)
    print("ix",ix)
    output=[]
    for i in range(len(xi)):
        if(i == ix):
            output.append(1)
        else:
            output.append(0)


    return(output)

def Forward_test(xi,L,weights,B):
    for j in range(len(L)-1):
        wixi=np.dot(xi,weights[j])+B[j]
        #print("wixi:",wixi)
        y=sigmoid(wixi)
        #print("y:",y)
        xi=y
        #print("wixi:",wixi)
        #print("y:",xi)
    return(op(y))

In [ ]:
def tanh(x):
     return((np.exp(x) - np.exp(-x) / (np.exp(x) + np.exp(-x))))
def sigmoid(x):
    return (1 / (1 + np.exp(-x)))
def relu(x):
    x=x.ravel()
    print(x)
    return max(0, x)
def relu_derivative(x):
    return np.where(x > 0, 1, 0)

def softmax(x):
    e_x = np.exp(x - np.max(x))  # Subtracting max(x) for numerical stability
    return e_x / e_x.sum(axis=0)
def softmax_derivative(x):
    s = softmax(x)
    d = -np.outer(s, s) + np.diag(s)
    return d
def Forward_propagation(xi,L,weights,B):
    output=[]
    output.append(xi)
    for j in range(len(L)-1):
        #print("xi:",xi)
        #print("weights:",weights[j])
        wixi=np.dot(xi,weights[j])+B[j]

        #print("wixi :",wixi)
        y=sigmoid(wixi)

        #print("y:",y)
        xi=y
        output.append(xi)

    #print("All output:",output)

    return(output)

In [ ]:
def sigmoid_derivative(y):
    return(y*(1-y))
def mean_square_error(x):
    x=x.ravel()
    #print(x)
    s=0
    for i in x:
        s=s+(0.5*(i**2))
    #print("s:",s)

    return(s)
def accuracy(D, Y):

    corr_pred = 0
    for d, y in zip(D, Y):
        if np.argmax(d) == np.argmax(y):
            corr_pred += 1

    acc = corr_pred / D.shape[0]

    return acc

In [ ]:
def backward_propagation(error,eta,outputs,weights,L,B):
    for i in range(L-1,-1,-1):
        y=outputs[i+1]
        gradient=np.array(eta*sigmoid_derivative(y)*(error))
        g=gradient
        current_output=outputs[i].T
        gradient=gradient.reshape(gradient.shape[0],-1).T
        current_output=current_output.reshape(current_output.shape[0],-1)
        #print("co",current_output)
       # print("gradinet:",gradient)
        #print(gradient.shape)
        s=gradient.shape
        if(s[0] != 1):
            gradient=gradient.T
        #print(s)
        delta_w=np.dot(current_output,gradient)
        weights[i]=weights[i]+delta_w
        #print("delta_w",delta_w)
        #print("gradinet:",gradient)

       # print("B:",B[i])
        B[i]=B[i]+(eta*gradient)
        #print("B after:",B[i])
        error=np.dot(g,weights[i].T)
    return(weights,B)

In [ ]:
class Multi_Layer_Perceptron:
    def __init__(self,Layers):
        self.L=Layers
        self.outputs=[]
        self.weights=[]
        self.Bias=[]
        for i in range(len(self.L)-1):
            b=np.zeros((1,self.L[i+1]))
            self.Bias.append(b)
       # print("Bias:",self.Bias)
        for i in range(len(self.L)-1):
            wt=np.random.rand(self.L[i],self.L[i+1])
            self.weights.append(wt)
        #print(self.weights)
    def train(self,x_train,y_train,eta):
        n=len(x_train)
        tot_error=0
        y_t=[]

        for i in range(n):
            xi=x_train[i]
            self.outputs=Forward_propagation(xi,self.L,self.weights,self.Bias)
            print("y:",y_train[i])
            print(self.outputs[-1])
            Error=(y_train[i]-self.outputs[-1])
            #print("main Error:",Error)
            error=mean_square_error(Error)
            #print("Error:",error)

            self.weights,self.Bias=backward_propagation(Error,eta,self.outputs,self.weights,len(self.L)-1,self.Bias)
        #print(self.weights)
        #print(self.Bias)

        #print("Total error:",tot_error/n)
    def test(self,x_test,Y_test):
        n=len(x_test)
        y_pred=[]
        for i in range(n):
            xi=x_test[i]
            pred=Forward_test(xi,self.L,self.weights,self.Bias)
            y_pred.append(pred)
        print(y_pred)
        accuracy1= accuracy(np.array(y_pred),Y_test)

        print(f"Accuracy: {accuracy1 * 100:.2f}%")



In [ ]:

X=data.iloc[:,:-1]
Y=data.iloc[:,-1]
no_hidden_layers = 1
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
Layers = []  # no. of neurons in each layer
Layers.append(X.shape[1])
neurons=int(input("Enter Number of neurons in hidden layer:"))
for i in range(no_hidden_layers):
    Layers.append(neurons)
Layers.append(2)
# Set parameters
eta = 0.005# Learning rate
epochs = 100
# No of iterations to run


print('No of nodes in each layer (input, hidden layers, output):' + str(Layers))

mlp = Multi_Layer_Perceptron(Layers)
for i in range(epochs):
    mlp.train(X_train.to_numpy(), Y_train.to_numpy(), eta)
print("Predicted Values are:")
mlp.test(X_test.to_numpy(), Y_test.to_numpy())

#mlp.testMLP(X_test, Y_test)

Enter Number of neurons in hidden layer:5
No of nodes in each layer (input, hidden layers, output):[8, 5, 2]
y: [1, 0]
[[0.51749991 0.52082245]]
y: [0, 1]
[[0.94737708 0.96939518]]
y: [1, 0]
[[0.63694904 0.66274246]]
y: [0, 1]
[[0.69603074 0.73892252]]
y: [1, 0]
[[0.8713588  0.91653006]]
y: [0, 1]
[[0.72001378 0.76193856]]
y: [1, 0]
[[0.61758633 0.63948176]]
y: [0, 1]
[[0.78646003 0.84042851]]
y: [0, 1]
[[0.93381802 0.96124603]]
y: [1, 0]
[[0.89301932 0.9353611 ]]
y: [1, 0]
[[0.87563522 0.91663415]]
y: [1, 0]
[[0.59417952 0.61538642]]
y: [0, 1]
[[0.88972696 0.92613968]]
y: [1, 0]
[[0.85807756 0.89489216]]
y: [0, 1]
[[0.90028911 0.93563396]]
y: [1, 0]
[[0.56808499 0.57506677]]
y: [0, 1]
[[0.89934259 0.93177835]]
y: [1, 0]
[[0.5480621  0.56073817]]
y: [1, 0]
[[0.85136306 0.8922527 ]]
y: [0, 1]
[[0.93839646 0.96080291]]
y: [1, 0]
[[0.51487964 0.51689871]]
y: [0, 1]
[[0.93789379 0.96431194]]
y: [0, 1]
[[0.88491776 0.92618112]]
y: [1, 0]
[[0.59981779 0.61443906]]
y: [1, 0]
[[0.57657051 0.60

y: [0, 1]
[[0.87651751 0.91865129]]
y: [1, 0]
[[0.59633639 0.60962829]]
y: [1, 0]
[[0.57356277 0.59751958]]
y: [0, 1]
[[0.94263869 0.9661074 ]]
y: [1, 0]
[[0.91998855 0.95004001]]
y: [0, 1]
[[0.94191288 0.96547432]]
y: [1, 0]
[[0.62495823 0.64967998]]
y: [1, 0]
[[0.70087043 0.73042443]]
y: [1, 0]
[[0.61266353 0.63036034]]
y: [1, 0]
[[0.91995427 0.94692178]]
y: [1, 0]
[[0.5054599  0.50430192]]
y: [0, 1]
[[0.8493555  0.88329808]]
y: [0, 1]
[[0.91212474 0.94089554]]
y: [1, 0]
[[0.89472758 0.93230001]]
y: [1, 0]
[[0.93009298 0.95792884]]
y: [1, 0]
[[0.86479247 0.89897684]]
y: [0, 1]
[[0.77080001 0.82204727]]
y: [0, 1]
[[0.92792701 0.95664041]]
y: [0, 1]
[[0.93227125 0.96066728]]
y: [0, 1]
[[0.91447168 0.94081406]]
y: [1, 0]
[[0.90205935 0.93840236]]
y: [0, 1]
[[0.92831533 0.95651005]]
y: [1, 0]
[[0.67457714 0.71527156]]
y: [1, 0]
[[0.80523517 0.84945331]]
y: [1, 0]
[[0.59115399 0.60179193]]
y: [0, 1]
[[0.70926107 0.72685793]]
y: [1, 0]
[[0.50201625 0.50152674]]
y: [1, 0]
[[0.7839014  0.829

[[0.70278743 0.7210695 ]]
y: [0, 1]
[[0.92663328 0.9536058 ]]
y: [1, 0]
[[0.68950793 0.71734413]]
y: [1, 0]
[[0.9272968  0.95467417]]
y: [1, 0]
[[0.87388717 0.91417779]]
y: [1, 0]
[[0.67907656 0.70270726]]
y: [0, 1]
[[0.712374   0.74235369]]
y: [1, 0]
[[0.55561132 0.5617233 ]]
y: [1, 0]
[[0.5909115  0.60673449]]
y: [0, 1]
[[0.87962518 0.91184708]]
y: [1, 0]
[[0.924289   0.95035301]]
y: [0, 1]
[[0.87618176 0.90840863]]
y: [0, 1]
[[0.87068489 0.92233148]]
y: [1, 0]
[[0.88460792 0.91545152]]
y: [1, 0]
[[0.52729423 0.52820829]]
y: [0, 1]
[[0.90325653 0.93177881]]
y: [1, 0]
[[0.78406159 0.83468222]]
y: [0, 1]
[[0.88853963 0.9224411 ]]
y: [1, 0]
[[0.82919557 0.88095654]]
y: [1, 0]
[[0.62254273 0.64365565]]
y: [1, 0]
[[0.76216493 0.80687974]]
y: [0, 1]
[[0.62868886 0.63921415]]
y: [1, 0]
[[0.53227513 0.53627685]]
y: [1, 0]
[[0.5012138  0.50077108]]
y: [1, 0]
[[0.53722064 0.55599298]]
y: [1, 0]
[[0.59833106 0.60908441]]
y: [1, 0]
[[0.59843954 0.6174844 ]]
y: [0, 1]
[[0.74656922 0.79484108]]
y:

[[0.71117034 0.7616918 ]]
y: [1, 0]
[[0.76789325 0.78991435]]
y: [1, 0]
[[0.57154066 0.59147166]]
y: [1, 0]
[[0.74497438 0.77798007]]
y: [0, 1]
[[0.80483632 0.80939565]]
y: [0, 1]
[[0.69880593 0.73713236]]
y: [1, 0]
[[0.64717253 0.66792091]]
y: [0, 1]
[[0.89484972 0.92623178]]
y: [1, 0]
[[0.9285183  0.95460631]]
y: [1, 0]
[[0.72049622 0.75478816]]
y: [1, 0]
[[0.6144021  0.64633741]]
y: [1, 0]
[[0.86797949 0.90966031]]
y: [0, 1]
[[0.91314412 0.94204039]]
y: [1, 0]
[[0.8281673  0.86028791]]
y: [0, 1]
[[0.82149279 0.86563984]]
y: [1, 0]
[[0.62465282 0.64902501]]
y: [0, 1]
[[0.80240526 0.84842111]]
y: [1, 0]
[[0.59907125 0.60740927]]
y: [0, 1]
[[0.6609628  0.68998669]]
y: [1, 0]
[[0.62247897 0.64059826]]
y: [0, 1]
[[0.89589586 0.92896002]]
y: [1, 0]
[[0.61360243 0.63158571]]
y: [1, 0]
[[0.59739434 0.62302637]]
y: [1, 0]
[[0.75585229 0.81065242]]
y: [1, 0]
[[0.72275647 0.77337857]]
y: [1, 0]
[[0.54970635 0.55210978]]
y: [0, 1]
[[0.93119964 0.95642536]]
y: [1, 0]
[[0.88708108 0.91747483]]
y:

y: [1, 0]
[[0.74689107 0.78994048]]
y: [0, 1]
[[0.62114373 0.62914836]]
y: [1, 0]
[[0.53021449 0.53330875]]
y: [1, 0]
[[0.50115766 0.50049787]]
y: [1, 0]
[[0.5340911 0.5515556]]
y: [1, 0]
[[0.59238499 0.60115083]]
y: [1, 0]
[[0.59178583 0.60866051]]
y: [0, 1]
[[0.73162136 0.77822878]]
y: [0, 1]
[[0.78503585 0.82722593]]
y: [1, 0]
[[0.86465074 0.90555737]]
y: [1, 0]
[[0.90501748 0.93293167]]
y: [1, 0]
[[0.77355339 0.79199142]]
y: [1, 0]
[[0.66368147 0.68839233]]
y: [1, 0]
[[0.82619991 0.8687988 ]]
y: [1, 0]
[[0.57722226 0.59651377]]
y: [1, 0]
[[0.52997767 0.53260151]]
y: [0, 1]
[[0.90895098 0.93920674]]
y: [0, 1]
[[0.71823138 0.7513726 ]]
y: [0, 1]
[[0.52712012 0.53080724]]
y: [1, 0]
[[0.56879132 0.58590455]]
y: [1, 0]
[[0.50851834 0.5121378 ]]
y: [1, 0]
[[0.54865647 0.55681842]]
y: [1, 0]
[[0.82456426 0.87406054]]
y: [1, 0]
[[0.5717786  0.59276057]]
y: [0, 1]
[[0.92012362 0.94784842]]
y: [1, 0]
[[0.80640447 0.83447412]]
y: [1, 0]
[[0.54593109 0.5566187 ]]
y: [1, 0]
[[0.87644585 0.92044

y: [1, 0]
[[0.7243025 0.7547811]]
y: [0, 1]
[[0.785331   0.78599991]]
y: [0, 1]
[[0.68089162 0.71707676]]
y: [1, 0]
[[0.63364205 0.65121003]]
y: [0, 1]
[[0.87349758 0.9066898 ]]
y: [1, 0]
[[0.90974639 0.93882215]]
y: [1, 0]
[[0.70165328 0.73278318]]
y: [1, 0]
[[0.60241637 0.631198  ]]
y: [1, 0]
[[0.84436287 0.88827473]]
y: [0, 1]
[[0.89285659 0.92384889]]
y: [1, 0]
[[0.80495535 0.83556753]]
y: [0, 1]
[[0.79802996 0.84287046]]
y: [1, 0]
[[0.61302963 0.6349258 ]]
y: [0, 1]
[[0.77867191 0.82456627]]
y: [1, 0]
[[0.59055599 0.59683837]]
y: [0, 1]
[[0.64612856 0.67253216]]
y: [1, 0]
[[0.61108157 0.6255737 ]]
y: [0, 1]
[[0.87408059 0.90909095]]
y: [1, 0]
[[0.60288068 0.61833858]]
y: [1, 0]
[[0.58720012 0.61002114]]
y: [1, 0]
[[0.73304783 0.78656271]]
y: [1, 0]
[[0.70216535 0.75138077]]
y: [1, 0]
[[0.54539185 0.54671003]]
y: [0, 1]
[[0.91271159 0.94090826]]
y: [1, 0]
[[0.86507976 0.89620847]]
y: [0, 1]
[[0.74813809 0.78608952]]
y: [0, 1]
[[0.74366923 0.77953378]]
y: [1, 0]
[[0.71525518 0.72972

y: [0, 1]
[[0.88498461 0.9123653 ]]
y: [1, 0]
[[0.51141836 0.51144469]]
y: [0, 1]
[[0.88124189 0.91742849]]
y: [0, 1]
[[0.81680051 0.86285057]]
y: [1, 0]
[[0.57589279 0.58264275]]
y: [1, 0]
[[0.55600025 0.57546757]]
y: [0, 1]
[[0.89635275 0.92768079]]
y: [1, 0]
[[0.86671724 0.90398605]]
y: [0, 1]
[[0.89535355 0.92664435]]
y: [1, 0]
[[0.5966441  0.61397284]]
y: [1, 0]
[[0.6607187  0.68214659]]
y: [1, 0]
[[0.58835682 0.60014168]]
y: [1, 0]
[[0.8694928  0.90038227]]
y: [1, 0]
[[0.50459764 0.5025172 ]]
y: [0, 1]
[[0.79122947 0.82249404]]
y: [0, 1]
[[0.85885261 0.89146699]]
y: [1, 0]
[[0.83645042 0.8801367 ]]
y: [1, 0]
[[0.87931289 0.91490101]]
y: [1, 0]
[[0.80739616 0.83750184]]
y: [0, 1]
[[0.71669497 0.76066295]]
y: [0, 1]
[[0.87636333 0.91305434]]
y: [0, 1]
[[0.88134048 0.91923602]]
y: [0, 1]
[[0.86202456 0.89110301]]
y: [1, 0]
[[0.84435278 0.88782995]]
y: [0, 1]
[[0.87671481 0.91314049]]
y: [1, 0]
[[0.63419234 0.66424196]]
y: [1, 0]
[[0.74658347 0.78539297]]
y: [1, 0]
[[0.57150595 0.576

y: [1, 0]
[[0.54296967 0.54445447]]
y: [1, 0]
[[0.56913096 0.57923515]]
y: [0, 1]
[[0.81732443 0.85018573]]
y: [1, 0]
[[0.86933622 0.90062048]]
y: [0, 1]
[[0.81579952 0.84964393]]
y: [0, 1]
[[0.80242406 0.86557706]]
y: [1, 0]
[[0.82281393 0.85468727]]
y: [1, 0]
[[0.5213944  0.52024535]]
y: [0, 1]
[[0.84371264 0.87502312]]
y: [1, 0]
[[0.72295482 0.77162446]]
y: [0, 1]
[[0.82609376 0.86342022]]
y: [1, 0]
[[0.76369174 0.82066197]]
y: [1, 0]
[[0.59349887 0.60617047]]
y: [1, 0]
[[0.70373953 0.74229945]]
y: [0, 1]
[[0.60099851 0.60323116]]
y: [1, 0]
[[0.5247724 0.5258183]]
y: [1, 0]
[[0.50100124 0.49983311]]
y: [1, 0]
[[0.52583538 0.5403281 ]]
y: [1, 0]
[[0.57660853 0.58088796]]
y: [1, 0]
[[0.57410003 0.5860429 ]]
y: [0, 1]
[[0.68974559 0.73198735]]
y: [0, 1]
[[0.73895829 0.77771829]]
y: [1, 0]
[[0.81592497 0.85975212]]
y: [1, 0]
[[0.86100613 0.89171739]]
y: [1, 0]
[[0.73291357 0.74342905]]
y: [1, 0]
[[0.63551635 0.65438434]]
y: [1, 0]
[[0.77841931 0.8213912 ]]
y: [1, 0]
[[0.56134326 0.57625

y: [0, 1]
[[0.75371789 0.79956827]]
y: [1, 0]
[[0.59325977 0.61168322]]
y: [0, 1]
[[0.73446457 0.77991832]]
y: [1, 0]
[[0.57615044 0.57959433]]
y: [0, 1]
[[0.62064225 0.6433299 ]]
y: [1, 0]
[[0.59165533 0.60082947]]
y: [0, 1]
[[0.82876827 0.86635469]]
y: [1, 0]
[[0.58466213 0.5965763 ]]
y: [1, 0]
[[0.56991972 0.58870655]]
y: [1, 0]
[[0.69187029 0.7430856 ]]
y: [1, 0]
[[0.66579882 0.71294713]]
y: [1, 0]
[[0.53814037 0.53798379]]
y: [0, 1]
[[0.87149449 0.90457882]]
y: [1, 0]
[[0.82013169 0.85163788]]
y: [0, 1]
[[0.70846913 0.74170086]]
y: [0, 1]
[[0.70513899 0.7387291 ]]
y: [1, 0]
[[0.68296473 0.69337953]]
y: [0, 1]
[[0.86858359 0.90189219]]
y: [1, 0]
[[0.82180724 0.85904611]]
y: [0, 1]
[[0.8547374  0.88709521]]
y: [1, 0]
[[0.55262263 0.56510331]]
y: [1, 0]
[[0.86737949 0.90167012]]
y: [1, 0]
[[0.57467732 0.576904  ]]
y: [0, 1]
[[0.71059009 0.75212679]]
y: [0, 1]
[[0.86032703 0.89183245]]
y: [0, 1]
[[0.75562711 0.79387232]]
y: [1, 0]
[[0.68520905 0.73567973]]
y: [0, 1]
[[0.80446094 0.839

y: [0, 1]
[[0.77481879 0.81634579]]
y: [1, 0]
[[0.74438502 0.78026285]]
y: [0, 1]
[[0.78284774 0.82271782]]
y: [1, 0]
[[0.54286332 0.54182495]]
y: [0, 1]
[[0.78374774 0.82003846]]
y: [1, 0]
[[0.52808768 0.53452407]]
y: [1, 0]
[[0.73428147 0.76928453]]
y: [0, 1]
[[0.83585556 0.86505298]]
y: [1, 0]
[[0.50931252 0.50840138]]
y: [0, 1]
[[0.82846189 0.8704021 ]]
y: [0, 1]
[[0.76228063 0.80975167]]
y: [1, 0]
[[0.56123547 0.56439789]]
y: [1, 0]
[[0.5434903  0.56061456]]
y: [0, 1]
[[0.84586031 0.88270451]]
y: [1, 0]
[[0.81280852 0.85479662]]
y: [0, 1]
[[0.84470859 0.88137174]]
y: [1, 0]
[[0.57614369 0.5894302 ]]
y: [1, 0]
[[0.63076725 0.64755529]]
y: [1, 0]
[[0.57087606 0.5795643 ]]
y: [1, 0]
[[0.81908114 0.85166471]]
y: [1, 0]
[[0.50397565 0.5013586 ]]
y: [0, 1]
[[0.74096365 0.76950703]]
y: [0, 1]
[[0.80650365 0.84076179]]
y: [1, 0]
[[0.78115879 0.82833699]]
y: [1, 0]
[[0.82627442 0.86691736]]
y: [1, 0]
[[0.75649156 0.78163279]]
y: [0, 1]
[[0.67401645 0.71239394]]
y: [0, 1]
[[0.82288923 0.864

[[0.5982021  0.63784548]]
y: [1, 0]
[[0.59859014 0.62451155]]
y: [0, 1]
[[0.72681119 0.75022516]]
y: [1, 0]
[[0.62238859 0.66521217]]
y: [1, 0]
[[0.67504296 0.68048898]]
y: [1, 0]
[[0.54173267 0.55302182]]
y: [1, 0]
[[0.65171006 0.67532715]]
y: [0, 1]
[[0.71382289 0.70328782]]
y: [0, 1]
[[0.62023633 0.65131615]]
y: [1, 0]
[[0.58897256 0.59859998]]
y: [0, 1]
[[0.77973629 0.81753459]]
y: [1, 0]
[[0.81748149 0.85561072]]
y: [1, 0]
[[0.63686778 0.6592793 ]]
y: [1, 0]
[[0.56329328 0.5840309 ]]
y: [1, 0]
[[0.74591583 0.7956575 ]]
y: [0, 1]
[[0.79853282 0.83375072]]
y: [1, 0]
[[0.71537312 0.7398939 ]]
y: [0, 1]
[[0.70839629 0.75521741]]
y: [1, 0]
[[0.57512876 0.5911098 ]]
y: [0, 1]
[[0.68994713 0.734983  ]]
y: [1, 0]
[[0.5630094  0.56448871]]
y: [0, 1]
[[0.59702578 0.61710814]]
y: [1, 0]
[[0.57382719 0.57893105]]
y: [0, 1]
[[0.77743312 0.81650281]]
y: [1, 0]
[[0.56797698 0.57738184]]
y: [1, 0]
[[0.55414783 0.56993993]]
y: [1, 0]
[[0.65177838 0.70094519]]
y: [1, 0]
[[0.63115865 0.67690533]]
y:

y: [1, 0]
[[0.5477439  0.56248162]]
y: [1, 0]
[[0.63489439 0.6832904 ]]
y: [1, 0]
[[0.61673775 0.66208619]]
y: [1, 0]
[[0.52891156 0.52742714]]
y: [0, 1]
[[0.79647586 0.83506293]]
y: [1, 0]
[[0.74730493 0.77796422]]
y: [0, 1]
[[0.65319639 0.68062014]]
y: [0, 1]
[[0.65176488 0.68338915]]
y: [1, 0]
[[0.63933927 0.64610519]]
y: [0, 1]
[[0.79339688 0.83197665]]
y: [1, 0]
[[0.74616871 0.78518051]]
y: [0, 1]
[[0.78075877 0.81535586]]
y: [1, 0]
[[0.53629727 0.54606845]]
y: [1, 0]
[[0.79144999 0.83157532]]
y: [1, 0]
[[0.55584945 0.55411649]]
y: [0, 1]
[[0.65835533 0.70213332]]
y: [0, 1]
[[0.78543712 0.82022535]]
y: [0, 1]
[[0.68873796 0.72233285]]
y: [1, 0]
[[0.62791939 0.67625752]]
y: [0, 1]
[[0.73195647 0.76544036]]
y: [0, 1]
[[0.71518322 0.73737277]]
y: [0, 1]
[[0.76496365 0.79547711]]
y: [1, 0]
[[0.70568818 0.72377587]]
y: [0, 1]
[[0.7225385  0.77694064]]
y: [0, 1]
[[0.7925703  0.83443886]]
y: [1, 0]
[[0.63692973 0.68164327]]
y: [1, 0]
[[0.73392469 0.76623485]]
y: [1, 0]
[[0.71153397 0.755

[[0.68612956 0.72148699]]
y: [0, 1]
[[0.71534116 0.75447864]]
y: [1, 0]
[[0.53286636 0.52975168]]
y: [0, 1]
[[0.71771089 0.7540875 ]]
y: [1, 0]
[[0.52023033 0.52505542]]
y: [1, 0]
[[0.67481006 0.7060006 ]]
y: [0, 1]
[[0.76803749 0.79807876]]
y: [1, 0]
[[0.50712831 0.50537093]]
y: [0, 1]
[[0.75529481 0.80259842]]
y: [0, 1]
[[0.69462569 0.74245942]]
y: [1, 0]
[[0.54587995 0.54604352]]
y: [1, 0]
[[0.53042329 0.5457235 ]]
y: [0, 1]
[[0.77357282 0.81561204]]
y: [1, 0]
[[0.74030655 0.78667577]]
y: [0, 1]
[[0.77241619 0.81409819]]
y: [1, 0]
[[0.55452786 0.56453139]]
y: [1, 0]
[[0.59850162 0.6115354 ]]
y: [1, 0]
[[0.55250438 0.55882052]]
y: [1, 0]
[[0.75174106 0.78517531]]
y: [1, 0]
[[0.50333481 0.50021084]]
y: [0, 1]
[[0.68093231 0.70666455]]
y: [0, 1]
[[0.73762123 0.77278212]]
y: [1, 0]
[[0.7106169 0.7606316]]
y: [1, 0]
[[0.7532192 0.7982583]]
y: [1, 0]
[[0.69467508 0.71344097]]
y: [0, 1]
[[0.62644418 0.65900988]]
y: [0, 1]
[[0.74969768 0.79617582]]
y: [0, 1]
[[0.75306044 0.80459897]]
y: [0,

y: [1, 0]
[[0.50660282 0.50545568]]
y: [0, 1]
[[0.73385331 0.77333614]]
y: [1, 0]
[[0.5486437  0.55393115]]
y: [0, 1]
[[0.5677057  0.59475805]]
y: [1, 0]
[[0.6491154 0.7032541]]
y: [0, 1]
[[0.58115592 0.61024745]]
y: [1, 0]
[[0.54161789 0.54531248]]
y: [0, 1]
[[0.60458256 0.65775379]]
y: [0, 1]
[[0.71020825 0.76005218]]
y: [1, 0]
[[0.6673302  0.72685486]]
y: [1, 0]
[[0.65783353 0.69503561]]
y: [1, 0]
[[0.53243022 0.53849663]]
y: [0, 1]
[[0.67744874 0.72028376]]
y: [1, 0]
[[0.65608919 0.691527  ]]
y: [0, 1]
[[0.67927162 0.71772695]]
y: [1, 0]
[[0.52813134 0.52418005]]
y: [0, 1]
[[0.68243138 0.71885502]]
y: [1, 0]
[[0.51651897 0.52069132]]
y: [1, 0]
[[0.64436688 0.67375405]]
y: [0, 1]
[[0.72971482 0.75995926]]
y: [1, 0]
[[0.50610666 0.5039702 ]]
y: [0, 1]
[[0.71399746 0.76357469]]
y: [0, 1]
[[0.65910478 0.70681977]]
y: [1, 0]
[[0.53860622 0.53755883]]
y: [1, 0]
[[0.52423351 0.53886363]]
y: [0, 1]
[[0.73188432 0.77612637]]
y: [1, 0]
[[0.70021446 0.74851177]]
y: [0, 1]
[[0.73082437 0.77463

[[0.57789603 0.6242257 ]]
y: [1, 0]
[[0.56849685 0.61345586]]
y: [1, 0]
[[0.52025463 0.51801974]]
y: [0, 1]
[[0.7005153  0.74328232]]
y: [1, 0]
[[0.66357543 0.69300616]]
y: [0, 1]
[[0.59755164 0.62026953]]
y: [0, 1]
[[0.59800828 0.6294636 ]]
y: [1, 0]
[[0.59621319 0.60162699]]
y: [0, 1]
[[0.69800906 0.74059369]]
y: [1, 0]
[[0.65865383 0.69874836]]
y: [0, 1]
[[0.69022902 0.72563992]]
y: [1, 0]
[[0.5210182  0.52900353]]
y: [1, 0]
[[0.69539729 0.74013217]]
y: [1, 0]
[[0.53820877 0.53359729]]
y: [0, 1]
[[0.60550743 0.65364851]]
y: [0, 1]
[[0.69252761 0.72954045]]
y: [0, 1]
[[0.61843165 0.64720955]]
y: [1, 0]
[[0.57098897 0.61819393]]
y: [0, 1]
[[0.65082238 0.68247798]]
y: [0, 1]
[[0.64170001 0.66258664]]
y: [0, 1]
[[0.67748083 0.70755069]]
y: [1, 0]
[[0.63536712 0.65011084]]
y: [0, 1]
[[0.64068225 0.70110739]]
y: [0, 1]
[[0.69557498 0.74314274]]
y: [1, 0]
[[0.57973823 0.62358704]]
y: [1, 0]
[[0.65236786 0.68098153]]
y: [1, 0]
[[0.63216509 0.67641885]]
y: [1, 0]
[[0.66764662 0.70945802]]
y:

[[0.59538671 0.59163398]]
y: [1, 0]
[[0.51965113 0.52651497]]
y: [1, 0]
[[0.57342008 0.59388453]]
y: [0, 1]
[[0.63188882 0.61547697]]
y: [0, 1]
[[0.55732173 0.58690045]]
y: [1, 0]
[[0.54409107 0.54911734]]
y: [0, 1]
[[0.64880798 0.69083597]]
y: [1, 0]
[[0.67059216 0.71568929]]
y: [1, 0]
[[0.5688346  0.58571992]]
y: [1, 0]
[[0.5246932  0.54004811]]
y: [1, 0]
[[0.61776778 0.67213895]]
y: [0, 1]
[[0.65839617 0.69369903]]
y: [1, 0]
[[0.60829514 0.62815185]]
y: [0, 1]
[[0.6022539  0.65289605]]
y: [1, 0]
[[0.5375544  0.55054918]]
y: [0, 1]
[[0.58783206 0.63349814]]
y: [1, 0]
[[0.5359165 0.53503  ]]
y: [0, 1]
[[0.54749936 0.56470658]]
y: [1, 0]
[[0.53711842 0.53555038]]
y: [0, 1]
[[0.64224668 0.68255539]]
y: [1, 0]
[[0.53349954 0.53967764]]
y: [1, 0]
[[0.5218184  0.53302546]]
y: [1, 0]
[[0.56358649 0.60954263]]
y: [1, 0]
[[0.55643313 0.60156292]]
y: [1, 0]
[[0.51813525 0.51578566]]
y: [0, 1]
[[0.67347061 0.71715681]]
y: [1, 0]
[[0.64114132 0.67036723]]
y: [0, 1]
[[0.58354835 0.60525336]]
y: [

[[0.64983237 0.69697515]]
y: [1, 0]
[[0.5267234 0.5336496]]
y: [1, 0]
[[0.55608603 0.5659764 ]]
y: [1, 0]
[[0.52885859 0.53327538]]
y: [1, 0]
[[0.6442314  0.67834549]]
y: [1, 0]
[[0.50257586 0.49876172]]
y: [0, 1]
[[0.59465997 0.61835113]]
y: [0, 1]
[[0.62950257 0.66579401]]
y: [1, 0]
[[0.60365345 0.65659755]]
y: [1, 0]
[[0.63405534 0.6833396 ]]
y: [1, 0]
[[0.60500881 0.61512576]]
y: [0, 1]
[[0.56260916 0.58795647]]
y: [0, 1]
[[0.63105855 0.68215271]]
y: [0, 1]
[[0.63096705 0.69004831]]
y: [0, 1]
[[0.63469521 0.66470377]]
y: [1, 0]
[[0.60624049 0.6616912 ]]
y: [0, 1]
[[0.63082789 0.68516053]]
y: [1, 0]
[[0.53192893 0.54285331]]
y: [1, 0]
[[0.56863006 0.59215226]]
y: [1, 0]
[[0.52403074 0.52070997]]
y: [0, 1]
[[0.56165766 0.53798828]]
y: [1, 0]
[[0.50097952 0.49819875]]
y: [1, 0]
[[0.56393594 0.59008076]]
y: [1, 0]
[[0.53658617 0.57212479]]
y: [1, 0]
[[0.53917275 0.56250218]]
y: [0, 1]
[[0.61291279 0.63364573]]
y: [1, 0]
[[0.53989466 0.57959937]]
y: [1, 0]
[[0.58353331 0.57878266]]
y: [

y: [1, 0]
[[0.52483714 0.52904074]]
y: [1, 0]
[[0.62398179 0.65827982]]
y: [1, 0]
[[0.50246432 0.49850583]]
y: [0, 1]
[[0.57920293 0.6028633 ]]
y: [0, 1]
[[0.60932879 0.64595944]]
y: [1, 0]
[[0.58409807 0.63752956]]
y: [1, 0]
[[0.61149815 0.66137893]]
y: [1, 0]
[[0.58899088 0.59761188]]
y: [0, 1]
[[0.55164336 0.5757    ]]
y: [0, 1]
[[0.60865962 0.6604614 ]]
y: [0, 1]
[[0.60782075 0.66807267]]
y: [0, 1]
[[0.61464377 0.64492572]]
y: [1, 0]
[[0.58602789 0.64209623]]
y: [0, 1]
[[0.60838553 0.66386427]]
y: [1, 0]
[[0.52511467 0.53484604]]
y: [1, 0]
[[0.55559219 0.57817319]]
y: [1, 0]
[[0.52089075 0.51720442]]
y: [0, 1]
[[0.55447912 0.52908755]]
y: [1, 0]
[[0.50095613 0.49803798]]
y: [1, 0]
[[0.5521345  0.57755416]]
y: [1, 0]
[[0.52965853 0.56493504]]
y: [1, 0]
[[0.53243417 0.55580176]]
y: [0, 1]
[[0.5990856 0.62001  ]]
y: [1, 0]
[[0.53049534 0.57013433]]
y: [1, 0]
[[0.57292613 0.56734027]]
y: [1, 0]
[[0.51382187 0.51952648]]
y: [1, 0]
[[0.5513753  0.57193933]]
y: [0, 1]
[[0.60795832 0.59150

y: [1, 0]
[[0.56357556 0.55728378]]
y: [1, 0]
[[0.51145077 0.51662944]]
y: [1, 0]
[[0.54215573 0.56292527]]
y: [0, 1]
[[0.59783131 0.58164212]]
y: [0, 1]
[[0.532525   0.56288223]]
y: [1, 0]
[[0.52682735 0.53080843]]
y: [0, 1]
[[0.59022212 0.63482783]]
y: [1, 0]
[[0.60120678 0.64863189]]
y: [1, 0]
[[0.54215899 0.55783945]]
y: [1, 0]
[[0.51011355 0.52372146]]
y: [1, 0]
[[0.56269402 0.61927285]]
y: [0, 1]
[[0.59446664 0.62927058]]
y: [1, 0]
[[0.56383096 0.58325528]]
y: [0, 1]
[[0.55805111 0.61178163]]
y: [1, 0]
[[0.52312969 0.53570221]]
y: [0, 1]
[[0.5460724  0.59325489]]
y: [1, 0]
[[0.52553949 0.5243243 ]]
y: [0, 1]
[[0.52829545 0.54542211]]
y: [1, 0]
[[0.52335582 0.51938083]]
y: [0, 1]
[[0.58232805 0.62302838]]
y: [1, 0]
[[0.52032555 0.52589077]]
y: [1, 0]
[[0.50966332 0.51939358]]
y: [1, 0]
[[0.52873101 0.57401667]]
y: [1, 0]
[[0.52695724 0.57311005]]
y: [1, 0]
[[0.5130177  0.51050122]]
y: [0, 1]
[[0.60359169 0.64943966]]
y: [1, 0]
[[0.58464311 0.61372984]]
y: [0, 1]
[[0.54945126 0.568

y: [0, 1]
[[0.56070038 0.59907515]]
y: [1, 0]
[[0.50526879 0.50753363]]
y: [1, 0]
[[0.54421915 0.56866942]]
y: [0, 1]
[[0.58953448 0.62153449]]
y: [1, 0]
[[0.50314642 0.4996335 ]]
y: [0, 1]
[[0.56448707 0.62043676]]
y: [0, 1]
[[0.53982255 0.5864738 ]]
y: [1, 0]
[[0.51650043 0.5119523 ]]
y: [1, 0]
[[0.50524101 0.51838229]]
y: [0, 1]
[[0.57746947 0.62771418]]
y: [1, 0]
[[0.55812591 0.61256815]]
y: [0, 1]
[[0.57722439 0.62692899]]
y: [1, 0]
[[0.51272738 0.51829792]]
y: [1, 0]
[[0.53429465 0.54320915]]
y: [1, 0]
[[0.5168526  0.52069898]]
y: [1, 0]
[[0.58248531 0.61726055]]
y: [1, 0]
[[0.50227854 0.49796697]]
y: [0, 1]
[[0.54797609 0.57196265]]
y: [0, 1]
[[0.56810897 0.60566064]]
y: [1, 0]
[[0.54447198 0.59891441]]
y: [1, 0]
[[0.56532471 0.61628949]]
y: [1, 0]
[[0.5569028  0.56231173]]
y: [0, 1]
[[0.52999065 0.55114277]]
y: [0, 1]
[[0.56282042 0.61601987]]
y: [0, 1]
[[0.56039888 0.62293332]]
y: [0, 1]
[[0.573629 0.604811]]
y: [1, 0]
[[0.54505104 0.60236548]]
y: [0, 1]
[[0.56241239 0.6203082

y: [1, 0]
[[0.54579326 0.55954462]]
y: [0, 1]
[[0.53314773 0.60350804]]
y: [0, 1]
[[0.55696614 0.61018319]]
y: [1, 0]
[[0.51047994 0.55525436]]
y: [1, 0]
[[0.54677298 0.56926782]]
y: [1, 0]
[[0.53069446 0.57539108]]
y: [1, 0]
[[0.54584041 0.59092456]]
y: [0, 1]
[[0.54166881 0.58394002]]
y: [1, 0]
[[0.50736231 0.50271433]]
y: [1, 0]
[[0.55243461 0.53572689]]
y: [1, 0]
[[0.53505303 0.52152662]]
y: [0, 1]
[[0.55174639 0.60094742]]
y: [1, 0]
[[0.51703313 0.526465  ]]
y: [1, 0]
[[0.55073328 0.60149325]]
y: [1, 0]
[[0.53817501 0.59702615]]
y: [1, 0]
[[0.5241938  0.53279327]]
y: [0, 1]
[[0.52713302 0.53112353]]
y: [1, 0]
[[0.50906924 0.50207581]]
y: [1, 0]
[[0.50928185 0.51116741]]
y: [0, 1]
[[0.54153    0.57283872]]
y: [1, 0]
[[0.56245983 0.60048595]]
y: [0, 1]
[[0.55362858 0.59573824]]
y: [0, 1]
[[0.50854262 0.59784977]]
y: [1, 0]
[[0.54429437 0.57664626]]
y: [1, 0]
[[0.5056217  0.50100734]]
y: [0, 1]
[[0.55055026 0.5854073 ]]
y: [1, 0]
[[0.51706015 0.56394006]]
y: [0, 1]
[[0.53968237 0.581

y: [0, 1]
[[0.53014327 0.58903692]]
y: [1, 0]
[[0.51734089 0.58026814]]
y: [1, 0]
[[0.5218451  0.55246044]]
y: [1, 0]
[[0.50555243 0.50749622]]
y: [0, 1]
[[0.53677015 0.58382072]]
y: [1, 0]
[[0.53328822 0.57421005]]
y: [0, 1]
[[0.52898035 0.56412177]]
y: [1, 0]
[[0.51091696 0.50390679]]
y: [0, 1]
[[0.53400072 0.57351671]]
y: [1, 0]
[[0.50308538 0.50480468]]
y: [1, 0]
[[0.52320283 0.54652594]]
y: [0, 1]
[[0.55774317 0.59068687]]
y: [1, 0]
[[0.50265162 0.4986639 ]]
y: [0, 1]
[[0.5310889  0.58838501]]
y: [0, 1]
[[0.51450726 0.56065711]]
y: [1, 0]
[[0.51219245 0.50665372]]
y: [1, 0]
[[0.50141113 0.51426   ]]
y: [0, 1]
[[0.54252631 0.59391855]]
y: [1, 0]
[[0.52671759 0.58272245]]
y: [0, 1]
[[0.5425169  0.59340503]]
y: [1, 0]
[[0.50643885 0.51125194]]
y: [1, 0]
[[0.52432025 0.53283654]]
y: [1, 0]
[[0.51137568 0.51499518]]
y: [1, 0]
[[0.55318138 0.58836113]]
y: [1, 0]
[[0.50220466 0.497546  ]]
y: [0, 1]
[[0.52613497 0.55073481]]
y: [0, 1]
[[0.53904266 0.57749601]]
y: [1, 0]
[[0.51678245 0.571

y: [0, 1]
[[0.51429744 0.53480619]]
y: [1, 0]
[[0.48856388 0.53687638]]
y: [0, 1]
[[0.52339091 0.55306454]]
y: [0, 1]
[[0.52681875 0.55214595]]
y: [0, 1]
[[0.53351678 0.56410135]]
y: [1, 0]
[[0.52776822 0.54186564]]
y: [0, 1]
[[0.51088504 0.58443261]]
y: [0, 1]
[[0.52813339 0.58232796]]
y: [1, 0]
[[0.49678501 0.54215768]]
y: [1, 0]
[[0.52605256 0.54640753]]
y: [1, 0]
[[0.51047373 0.55525569]]
y: [1, 0]
[[0.52091216 0.56691904]]
y: [0, 1]
[[0.52060299 0.56309108]]
y: [1, 0]
[[0.50517896 0.49986981]]
y: [1, 0]
[[0.53944961 0.52172074]]
y: [1, 0]
[[0.52724233 0.51208153]]
y: [0, 1]
[[0.52464167 0.57492695]]
y: [1, 0]
[[0.50857577 0.51793807]]
y: [1, 0]
[[0.52362468 0.57517675]]
y: [1, 0]
[[0.51709751 0.57773091]]
y: [1, 0]
[[0.51651373 0.52541881]]
y: [0, 1]
[[0.51821759 0.52120862]]
y: [1, 0]
[[0.50720814 0.49930474]]
y: [1, 0]
[[0.50560721 0.50700521]]
y: [0, 1]
[[0.52024835 0.55231604]]
y: [1, 0]
[[0.53662109 0.57509085]]
y: [0, 1]
[[0.53286674 0.57740938]]
y: [0, 1]
[[0.48647848 0.577

[[0.50620257 0.5113589 ]]
y: [1, 0]
[[0.49709667 0.50461644]]
y: [1, 0]
[[0.49113712 0.53588047]]
y: [1, 0]
[[0.49439705 0.54343604]]
y: [1, 0]
[[0.50749206 0.50497566]]
y: [0, 1]
[[0.52345315 0.57168183]]
y: [1, 0]
[[0.5214167  0.55105058]]
y: [0, 1]
[[0.51306751 0.52923747]]
y: [0, 1]
[[0.51332159 0.55118384]]
y: [1, 0]
[[0.52873842 0.53893011]]
y: [0, 1]
[[0.52334    0.57131199]]
y: [1, 0]
[[0.51004249 0.55309635]]
y: [0, 1]
[[0.52937365 0.56500307]]
y: [1, 0]
[[0.4990324 0.5049246]]
y: [1, 0]
[[0.52055433 0.5712109 ]]
y: [1, 0]
[[0.51323673 0.50415675]]
y: [0, 1]
[[0.51932018 0.58571678]]
y: [0, 1]
[[0.52519852 0.56669548]]
y: [0, 1]
[[0.5093602  0.52909388]]
y: [1, 0]
[[0.48448179 0.53300664]]
y: [0, 1]
[[0.51703267 0.54655713]]
y: [0, 1]
[[0.52086601 0.54688273]]
y: [0, 1]
[[0.52616118 0.55681959]]
y: [1, 0]
[[0.52235172 0.5366031 ]]
y: [0, 1]
[[0.50408577 0.57883217]]
y: [0, 1]
[[0.51946568 0.57394534]]
y: [1, 0]
[[0.49266922 0.53827628]]
y: [1, 0]
[[0.51996388 0.53945841]]
y: [

[[0.49754551 0.56324892]]
y: [0, 1]
[[0.51907102 0.55258372]]
y: [1, 0]
[[0.49139385 0.55052098]]
y: [0, 1]
[[0.50125335 0.56315337]]
y: [1, 0]
[[0.49614369 0.49729379]]
y: [1, 0]
[[0.49718497 0.51369484]]
y: [1, 0]
[[0.50713831 0.50117264]]
y: [0, 1]
[[0.52452529 0.48679319]]
y: [1, 0]
[[0.50111953 0.49705244]]
y: [1, 0]
[[0.49910176 0.52008782]]
y: [1, 0]
[[0.49837607 0.53253827]]
y: [1, 0]
[[0.50130621 0.52634609]]
y: [0, 1]
[[0.53378465 0.55837159]]
y: [1, 0]
[[0.48751158 0.52786367]]
y: [1, 0]
[[0.52498082 0.51514555]]
y: [1, 0]
[[0.50237052 0.50402702]]
y: [1, 0]
[[0.50291716 0.52636437]]
y: [0, 1]
[[0.55364951 0.54190128]]
y: [0, 1]
[[0.50122414 0.5348903 ]]
y: [1, 0]
[[0.50600724 0.50876792]]
y: [0, 1]
[[0.51426763 0.56468056]]
y: [1, 0]
[[0.51106248 0.56134428]]
y: [1, 0]
[[0.5096509  0.52413285]]
y: [1, 0]
[[0.49317467 0.50357439]]
y: [1, 0]
[[0.49279775 0.55380929]]
y: [0, 1]
[[0.51297953 0.5462995 ]]
y: [1, 0]
[[0.50802175 0.52875245]]
y: [0, 1]
[[0.50115083 0.56284644]]
y:

[[0.50119084 0.49692197]]
y: [1, 0]
[[0.49545491 0.51572177]]
y: [1, 0]
[[0.4961493  0.53014807]]
y: [1, 0]
[[0.49893891 0.52432254]]
y: [0, 1]
[[0.52876016 0.55403533]]
y: [1, 0]
[[0.48434234 0.52485432]]
y: [1, 0]
[[0.52165352 0.5112082 ]]
y: [1, 0]
[[0.50174348 0.50271858]]
y: [1, 0]
[[0.49921195 0.52323423]]
y: [0, 1]
[[0.54930849 0.53859478]]
y: [0, 1]
[[0.49820496 0.53255078]]
y: [1, 0]
[[0.5041868  0.50674545]]
y: [0, 1]
[[0.50707896 0.55847835]]
y: [1, 0]
[[0.50276956 0.55332384]]
y: [1, 0]
[[0.50676787 0.52105833]]
y: [1, 0]
[[0.49182111 0.50161667]]
y: [1, 0]
[[0.48628364 0.54801962]]
y: [0, 1]
[[0.50566504 0.53858523]]
y: [1, 0]
[[0.50287878 0.52391795]]
y: [0, 1]
[[0.49558761 0.55877646]]
y: [1, 0]
[[0.50386714 0.51653215]]
y: [0, 1]
[[0.48831507 0.54100173]]
y: [1, 0]
[[0.51166224 0.5105558 ]]
y: [0, 1]
[[0.50224637 0.52079393]]
y: [1, 0]
[[0.50666529 0.49697849]]
y: [0, 1]
[[0.49945572 0.54069277]]
y: [1, 0]
[[0.50294109 0.50797116]]
y: [1, 0]
[[0.49445045 0.5009399 ]]
y:

y: [0, 1]
[[0.49785804 0.53058401]]
y: [1, 0]
[[0.501778  0.4981871]]
y: [0, 1]
[[0.48525731 0.54918342]]
y: [0, 1]
[[0.48825327 0.55047857]]
y: [1, 0]
[[0.48436639 0.5474708 ]]
y: [1, 0]
[[0.49327736 0.5203156 ]]
y: [1, 0]
[[0.50055037 0.50052753]]
y: [0, 1]
[[0.50462423 0.55431226]]
y: [1, 0]
[[0.50471243 0.55023781]]
y: [0, 1]
[[0.49628772 0.52949611]]
y: [1, 0]
[[0.50780182 0.49928531]]
y: [0, 1]
[[0.50009444 0.54210714]]
y: [1, 0]
[[0.50068205 0.50115372]]
y: [1, 0]
[[0.4976949  0.51849625]]
y: [0, 1]
[[0.51734385 0.55215503]]
y: [1, 0]
[[0.50231141 0.49720354]]
y: [0, 1]
[[0.48901395 0.54832448]]
y: [0, 1]
[[0.4834973  0.52811202]]
y: [1, 0]
[[0.50740599 0.4996073 ]]
y: [1, 0]
[[0.49681326 0.5090384 ]]
y: [0, 1]
[[0.49852853 0.55135455]]
y: [1, 0]
[[0.48702439 0.54575302]]
y: [0, 1]
[[0.49878861 0.55124479]]
y: [1, 0]
[[0.49906775 0.50220305]]
y: [1, 0]
[[0.51212474 0.51986274]]
y: [1, 0]
[[0.50468657 0.50787338]]
y: [1, 0]
[[0.51641073 0.55201591]]
y: [1, 0]
[[0.50231337 0.49682

y: [1, 0]
[[0.47741825 0.53716317]]
y: [0, 1]
[[0.48499733 0.54858418]]
y: [1, 0]
[[0.49307364 0.49086471]]
y: [1, 0]
[[0.4894878  0.50366866]]
y: [1, 0]
[[0.50543011 0.49861336]]
y: [0, 1]
[[0.5217683  0.47925366]]
y: [1, 0]
[[0.501296   0.49675814]]
y: [1, 0]
[[0.49196929 0.51126247]]
y: [1, 0]
[[0.49397144 0.5277403 ]]
y: [1, 0]
[[0.49653457 0.52236593]]
y: [0, 1]
[[0.52365735 0.54981776]]
y: [1, 0]
[[0.48117729 0.52188629]]
y: [1, 0]
[[0.51846201 0.50719782]]
y: [1, 0]
[[0.50124088 0.50130632]]
y: [1, 0]
[[0.4954423  0.52021395]]
y: [0, 1]
[[0.54481059 0.53547162]]
y: [0, 1]
[[0.49509395 0.53032838]]
y: [1, 0]
[[0.50241909 0.50470295]]
y: [0, 1]
[[0.4997948  0.55243689]]
y: [1, 0]
[[0.49452425 0.54535333]]
y: [1, 0]
[[0.503945   0.51796909]]
y: [1, 0]
[[0.49058719 0.49957405]]
y: [1, 0]
[[0.4797182  0.54236089]]
y: [0, 1]
[[0.4984963  0.53083087]]
y: [1, 0]
[[0.49773126 0.51915744]]
y: [0, 1]
[[0.48982206 0.55494849]]
y: [1, 0]
[[0.50226669 0.51497875]]
y: [0, 1]
[[0.48320842 0.537

y: [0, 1]
[[0.49692176 0.55015844]]
y: [1, 0]
[[0.491341   0.54227667]]
y: [1, 0]
[[0.50287438 0.51675963]]
y: [1, 0]
[[0.49016054 0.49874102]]
y: [1, 0]
[[0.47714274 0.5402172 ]]
y: [0, 1]
[[0.49577505 0.52779676]]
y: [1, 0]
[[0.49572839 0.51733678]]
y: [0, 1]
[[0.4874911  0.55356578]]
y: [1, 0]
[[0.50164725 0.51437943]]
y: [0, 1]
[[0.48117818 0.53556394]]
y: [1, 0]
[[0.51005284 0.50901914]]
y: [0, 1]
[[0.49910368 0.51815855]]
y: [1, 0]
[[0.50539261 0.49387034]]
y: [0, 1]
[[0.49002404 0.53113848]]
y: [1, 0]
[[0.50101216 0.50590576]]
y: [1, 0]
[[0.49307665 0.49852962]]
y: [1, 0]
[[0.4773177  0.52150629]]
y: [1, 0]
[[0.48132241 0.53320093]]
y: [1, 0]
[[0.50539906 0.50293953]]
y: [0, 1]
[[0.49282361 0.54199849]]
y: [1, 0]
[[0.49749455 0.52743211]]
y: [0, 1]
[[0.50041985 0.51358448]]
y: [0, 1]
[[0.49782483 0.54008626]]
y: [1, 0]
[[0.51620971 0.53030519]]
y: [0, 1]
[[0.49318332 0.54213819]]
y: [1, 0]
[[0.4849214  0.52904451]]
y: [0, 1]
[[0.50236826 0.53711631]]
y: [1, 0]
[[0.49583562 0.500

[[0.50048976 0.49606986]]
y: [0, 1]
[[0.49069263 0.51689864]]
y: [1, 0]
[[0.47280066 0.53101409]]
y: [0, 1]
[[0.49408913 0.52788523]]
y: [1, 0]
[[0.50068338 0.49592959]]
y: [0, 1]
[[0.47959302 0.54571515]]
y: [0, 1]
[[0.4784451  0.54198551]]
y: [1, 0]
[[0.47698576 0.53992197]]
y: [1, 0]
[[0.48736123 0.5125237 ]]
y: [1, 0]
[[0.49969491 0.49868834]]
y: [0, 1]
[[0.49704782 0.54783247]]
y: [1, 0]
[[0.49764303 0.54530914]]
y: [0, 1]
[[0.48921934 0.52132188]]
y: [1, 0]
[[0.5073081  0.49804054]]
y: [0, 1]
[[0.49213605 0.5352128 ]]
y: [1, 0]
[[0.50031222 0.50015906]]
y: [1, 0]
[[0.49231228 0.51179096]]
y: [0, 1]
[[0.50799512 0.54349472]]
y: [1, 0]
[[0.50238923 0.49672204]]
y: [0, 1]
[[0.47935401 0.53931433]]
y: [0, 1]
[[0.47677378 0.52046766]]
y: [1, 0]
[[0.50664004 0.49771073]]
y: [1, 0]
[[0.49586151 0.50776639]]
y: [0, 1]
[[0.48851109 0.54166321]]
y: [1, 0]
[[0.47779692 0.53756865]]
y: [0, 1]
[[0.48881114 0.54166797]]
y: [1, 0]
[[0.49764429 0.49993367]]
y: [1, 0]
[[0.50947958 0.51680578]]
y:

[[0.48893039 0.53822226]]
y: [1, 0]
[[0.49447145 0.52442012]]
y: [0, 1]
[[0.49901952 0.51140994]]
y: [0, 1]
[[0.49559466 0.53891062]]
y: [1, 0]
[[0.51437862 0.52942394]]
y: [0, 1]
[[0.48934705 0.53842986]]
y: [1, 0]
[[0.48170737 0.5260212 ]]
y: [0, 1]
[[0.49903736 0.53347524]]
y: [1, 0]
[[0.49549005 0.50026322]]
y: [1, 0]
[[0.48668132 0.53841816]]
y: [1, 0]
[[0.50976535 0.49795694]]
y: [0, 1]
[[0.49814266 0.57805884]]
y: [0, 1]
[[0.49247798 0.53572542]]
y: [0, 1]
[[0.49158346 0.50538792]]
y: [1, 0]
[[0.46825358 0.51820804]]
y: [0, 1]
[[0.49260066 0.52068286]]
y: [0, 1]
[[0.49642577 0.52734992]]
y: [0, 1]
[[0.49743287 0.52816582]]
y: [1, 0]
[[0.50096668 0.51621821]]
y: [0, 1]
[[0.47566145 0.55851083]]
y: [0, 1]
[[0.48546421 0.54100014]]
y: [1, 0]
[[0.47627708 0.52342433]]
y: [1, 0]
[[0.49788273 0.51067314]]
y: [1, 0]
[[0.48102142 0.52542375]]
y: [1, 0]
[[0.48380479 0.53185977]]
y: [0, 1]
[[0.48973866 0.53222832]]
y: [1, 0]
[[0.50262976 0.49511942]]
y: [1, 0]
[[0.52126175 0.50044   ]]
y:

[[0.48818794 0.53085914]]
y: [1, 0]
[[0.50104747 0.51499733]]
y: [1, 0]
[[0.49801555 0.49718378]]
y: [1, 0]
[[0.46014722 0.53543507]]
y: [1, 0]
[[0.5009854  0.49711642]]
y: [0, 1]
[[0.49320781 0.49856095]]
y: [0, 1]
[[0.50625533 0.52661175]]
y: [0, 1]
[[0.51264149 0.53656433]]
y: [1, 0]
[[0.50721967 0.49954885]]
y: [1, 0]
[[0.5016456  0.49680363]]
y: [0, 1]
[[0.48843656 0.53413456]]
y: [1, 0]
[[0.50016591 0.4950743 ]]
y: [0, 1]
[[0.48966935 0.5159376 ]]
y: [1, 0]
[[0.47042349 0.52879614]]
y: [0, 1]
[[0.49273196 0.52704694]]
y: [1, 0]
[[0.50041318 0.49507404]]
y: [0, 1]
[[0.47751012 0.54470239]]
y: [0, 1]
[[0.47505053 0.53919515]]
y: [1, 0]
[[0.47452621 0.5373386 ]]
y: [1, 0]
[[0.48553438 0.50973649]]
y: [1, 0]
[[0.49948938 0.49798756]]
y: [0, 1]
[[0.49441385 0.5457049 ]]
y: [1, 0]
[[0.49508913 0.54378947]]
y: [0, 1]
[[0.48694151 0.51846117]]
y: [1, 0]
[[0.50720479 0.49756001]]
y: [0, 1]
[[0.48937766 0.53294831]]
y: [1, 0]
[[0.50023961 0.4997722 ]]
y: [1, 0]
[[0.49061795 0.50941524]]
y:

y: [1, 0]
[[0.46678117 0.51698418]]
y: [0, 1]
[[0.49059149 0.5183223 ]]
y: [0, 1]
[[0.49404212 0.52588406]]
y: [0, 1]
[[0.49496644 0.52563047]]
y: [1, 0]
[[0.49907155 0.51447546]]
y: [0, 1]
[[0.47276801 0.55711381]]
y: [0, 1]
[[0.48250654 0.53811606]]
y: [1, 0]
[[0.47478367 0.52219518]]
y: [1, 0]
[[0.49638114 0.50778067]]
y: [1, 0]
[[0.47904019 0.52329548]]
y: [1, 0]
[[0.48117528 0.52947799]]
y: [0, 1]
[[0.48763896 0.53003932]]
y: [1, 0]
[[0.50257679 0.49467502]]
y: [1, 0]
[[0.52018299 0.49880044]]
y: [1, 0]
[[0.51697116 0.49551454]]
y: [0, 1]
[[0.48141364 0.53416093]]
y: [1, 0]
[[0.49543111 0.50457533]]
y: [1, 0]
[[0.48082498 0.53354261]]
y: [1, 0]
[[0.48238404 0.54864474]]
y: [1, 0]
[[0.50406219 0.51424419]]
y: [0, 1]
[[0.50544916 0.50458881]]
y: [1, 0]
[[0.50541102 0.49393036]]
y: [1, 0]
[[0.50044562 0.49996012]]
y: [0, 1]
[[0.48611748 0.52070247]]
y: [1, 0]
[[0.4958798  0.53473914]]
y: [0, 1]
[[0.49752256 0.55080408]]
y: [0, 1]
[[0.45065169 0.5466499 ]]
y: [1, 0]
[[0.48732267 0.524

[[0.51600862 0.54422894]]
y: [1, 0]
[[0.47664407 0.51776482]]
y: [1, 0]
[[0.51445397 0.50108956]]
y: [1, 0]
[[0.50104508 0.49882631]]
y: [1, 0]
[[0.48975312 0.51630429]]
y: [0, 1]
[[0.53770078 0.53172549]]
y: [0, 1]
[[0.490236   0.52760262]]
y: [1, 0]
[[0.50010185 0.50166164]]
y: [0, 1]
[[0.48893598 0.54441138]]
y: [1, 0]
[[0.48288633 0.53409707]]
y: [1, 0]
[[0.50014382 0.51343721]]
y: [1, 0]
[[0.4893194  0.49626026]]
y: [1, 0]
[[0.47005937 0.53474895]]
y: [0, 1]
[[0.48882073 0.51948406]]
y: [1, 0]
[[0.49031762 0.51258471]]
y: [0, 1]
[[0.48068333 0.5504384 ]]
y: [1, 0]
[[0.49999325 0.51278309]]
y: [0, 1]
[[0.47543958 0.53196947]]
y: [1, 0]
[[0.50884466 0.50788697]]
y: [0, 1]
[[0.49663773 0.51632217]]
y: [1, 0]
[[0.50502257 0.49104079]]
y: [0, 1]
[[0.48317058 0.52396071]]
y: [1, 0]
[[0.49964001 0.50432668]]
y: [1, 0]
[[0.49238865 0.49644205]]
y: [1, 0]
[[0.47365783 0.51737104]]
y: [1, 0]
[[0.4771702  0.53081499]]
y: [1, 0]
[[0.5048071  0.50236993]]
y: [0, 1]
[[0.48430525 0.53372451]]
y:

y: [0, 1]
[[0.50491173 0.50325505]]
y: [1, 0]
[[0.50554666 0.49334841]]
y: [1, 0]
[[0.50025191 0.49937817]]
y: [0, 1]
[[0.48380803 0.51878498]]
y: [1, 0]
[[0.4933138  0.53208068]]
y: [0, 1]
[[0.49470076 0.54957279]]
y: [0, 1]
[[0.44808663 0.54490327]]
y: [1, 0]
[[0.48485414 0.52276009]]
y: [1, 0]
[[0.50375058 0.49723942]]
y: [0, 1]
[[0.48579015 0.52654923]]
y: [1, 0]
[[0.47822215 0.52827236]]
y: [0, 1]
[[0.47907394 0.52587561]]
y: [1, 0]
[[0.46490825 0.55602088]]
y: [1, 0]
[[0.50335222 0.4930679 ]]
y: [1, 0]
[[0.48217264 0.50576577]]
y: [0, 1]
[[0.51390029 0.49562834]]
y: [1, 0]
[[0.50311257 0.49494481]]
y: [1, 0]
[[0.50142658 0.49630477]]
y: [1, 0]
[[0.49322108 0.49372091]]
y: [1, 0]
[[0.50938892 0.49827884]]
y: [1, 0]
[[0.49884032 0.49303446]]
y: [0, 1]
[[0.47941836 0.50813266]]
y: [0, 1]
[[0.48541587 0.508616  ]]
y: [1, 0]
[[0.47680878 0.52065003]]
y: [1, 0]
[[0.48774743 0.52272848]]
y: [1, 0]
[[0.517775   0.50012706]]
y: [1, 0]
[[0.50663494 0.50971401]]
y: [1, 0]
[[0.48311509 0.533

y: [0, 1]
[[0.49089702 0.53728581]]
y: [1, 0]
[[0.51046458 0.52829492]]
y: [0, 1]
[[0.48231608 0.53161608]]
y: [1, 0]
[[0.47576555 0.52052968]]
y: [0, 1]
[[0.49318323 0.52655332]]
y: [1, 0]
[[0.4950005  0.49907484]]
y: [1, 0]
[[0.47968926 0.53161556]]
y: [1, 0]
[[0.50961019 0.4961474 ]]
y: [0, 1]
[[0.4911217  0.57881344]]
y: [0, 1]
[[0.48555675 0.52945542]]
y: [0, 1]
[[0.48920089 0.4993196 ]]
y: [1, 0]
[[0.46470014 0.5153708 ]]
y: [0, 1]
[[0.48797596 0.51496024]]
y: [0, 1]
[[0.49049993 0.52412712]]
y: [0, 1]
[[0.49163509 0.52210533]]
y: [1, 0]
[[0.49644452 0.51211414]]
y: [0, 1]
[[0.46834459 0.55560722]]
y: [0, 1]
[[0.47846505 0.53414653]]
y: [1, 0]
[[0.47266682 0.52057431]]
y: [1, 0]
[[0.49479633 0.50338091]]
y: [1, 0]
[[0.47639316 0.52030908]]
y: [1, 0]
[[0.47752142 0.52625909]]
y: [0, 1]
[[0.48481089 0.52698226]]
y: [1, 0]
[[0.50263267 0.49394538]]
y: [1, 0]
[[0.51889867 0.49637546]]
y: [1, 0]
[[0.51675885 0.49339304]]
y: [0, 1]
[[0.47745042 0.530634  ]]
y: [1, 0]
[[0.49431917 0.503

y: [1, 0]
[[0.4949666  0.49888334]]
y: [1, 0]
[[0.47874655 0.53068992]]
y: [1, 0]
[[0.50966362 0.49583183]]
y: [0, 1]
[[0.48982559 0.57921986]]
y: [0, 1]
[[0.48460217 0.52862169]]
y: [0, 1]
[[0.48904971 0.49834076]]
y: [1, 0]
[[0.46419364 0.51501279]]
y: [0, 1]
[[0.48740783 0.5141329 ]]
y: [0, 1]
[[0.48958496 0.52379459]]
y: [0, 1]
[[0.49087153 0.5212639 ]]
y: [1, 0]
[[0.4958209  0.51156949]]
y: [0, 1]
[[0.46716593 0.55538234]]
y: [0, 1]
[[0.47752365 0.53321176]]
y: [1, 0]
[[0.47214977 0.52021449]]
y: [1, 0]
[[0.49457476 0.50221366]]
y: [1, 0]
[[0.47579567 0.51958766]]
y: [1, 0]
[[0.47665112 0.52551942]]
y: [0, 1]
[[0.48416524 0.52624832]]
y: [1, 0]
[[0.50268626 0.49373657]]
y: [1, 0]
[[0.51865953 0.49575156]]
y: [1, 0]
[[0.51680805 0.49280421]]
y: [0, 1]
[[0.47650816 0.52982102]]
y: [1, 0]
[[0.49406758 0.5030513 ]]
y: [1, 0]
[[0.47616276 0.52892475]]
y: [1, 0]
[[0.4778911  0.54602764]]
y: [1, 0]
[[0.50252929 0.51314542]]
y: [0, 1]
[[0.50465242 0.50219234]]
y: [1, 0]
[[0.50575011 0.492

y: [1, 0]
[[0.48897763 0.54131277]]
y: [0, 1]
[[0.48274038 0.5120008 ]]
y: [1, 0]
[[0.50729935 0.49626406]]
y: [0, 1]
[[0.48330434 0.52852722]]
y: [1, 0]
[[0.50034421 0.49871614]]
y: [1, 0]
[[0.48769868 0.50391115]]
y: [0, 1]
[[0.49799798 0.53468723]]
y: [1, 0]
[[0.5028364  0.49586235]]
y: [0, 1]
[[0.46909786 0.53013219]]
y: [0, 1]
[[0.4705291  0.51182729]]
y: [1, 0]
[[0.50660123 0.49500672]]
y: [1, 0]
[[0.49509305 0.50621028]]
y: [0, 1]
[[0.47810889 0.53154239]]
y: [1, 0]
[[0.46771769 0.52951121]]
y: [0, 1]
[[0.47839925 0.53171431]]
y: [1, 0]
[[0.49675481 0.49702243]]
y: [1, 0]
[[0.50703066 0.51330079]]
y: [1, 0]
[[0.50189089 0.50426302]]
y: [1, 0]
[[0.49965063 0.53474241]]
y: [1, 0]
[[0.50286213 0.4960009 ]]
y: [0, 1]
[[0.48513565 0.51346254]]
y: [0, 1]
[[0.48486183 0.52682831]]
y: [1, 0]
[[0.46606426 0.52314722]]
y: [1, 0]
[[0.47392843 0.525346  ]]
y: [1, 0]
[[0.50114474 0.4871483 ]]
y: [0, 1]
[[0.49515822 0.49717187]]
y: [0, 1]
[[0.4711775  0.52747899]]
y: [0, 1]
[[0.46471545 0.533

y: [1, 0]
[[0.50097353 0.49571875]]
y: [0, 1]
[[0.49273946 0.49629753]]
y: [0, 1]
[[0.49974956 0.5226312 ]]
y: [0, 1]
[[0.50681431 0.53585888]]
y: [1, 0]
[[0.5071562  0.49886263]]
y: [1, 0]
[[0.50203757 0.49603606]]
y: [0, 1]
[[0.48071136 0.52656069]]
y: [1, 0]
[[0.50014706 0.49212033]]
y: [0, 1]
[[0.48728273 0.51374325]]
y: [1, 0]
[[0.46489675 0.52379017]]
y: [0, 1]
[[0.48910562 0.52556724]]
y: [1, 0]
[[0.50042098 0.49252233]]
y: [0, 1]
[[0.47168586 0.54335435]]
y: [0, 1]
[[0.46677208 0.5332712 ]]
y: [1, 0]
[[0.46910882 0.53118861]]
y: [1, 0]
[[0.48243169 0.50235108]]
y: [1, 0]
[[0.49954421 0.49587607]]
y: [0, 1]
[[0.48792891 0.54119185]]
y: [1, 0]
[[0.48821645 0.54119161]]
y: [0, 1]
[[0.48242123 0.51125616]]
y: [1, 0]
[[0.50736711 0.49607828]]
y: [0, 1]
[[0.4826339  0.52813703]]
y: [1, 0]
[[0.50040293 0.49856282]]
y: [1, 0]
[[0.48752061 0.50325265]]
y: [0, 1]
[[0.49728768 0.53411568]]
y: [1, 0]
[[0.50291626 0.49575549]]
y: [0, 1]
[[0.46837684 0.52953341]]
y: [0, 1]
[[0.47020846 0.511

[[0.48279757 0.52709219]]
y: [0, 1]
[[0.48904763 0.49626114]]
y: [1, 0]
[[0.46321001 0.51438725]]
y: [0, 1]
[[0.48644524 0.51250537]]
y: [0, 1]
[[0.48769924 0.52334251]]
y: [0, 1]
[[0.48948581 0.51966154]]
y: [1, 0]
[[0.4946422  0.51057174]]
y: [0, 1]
[[0.46466682 0.55523522]]
y: [0, 1]
[[0.47578194 0.5314585 ]]
y: [1, 0]
[[0.47114189 0.51958542]]
y: [1, 0]
[[0.49448211 0.49974628]]
y: [1, 0]
[[0.47473148 0.51819564]]
y: [1, 0]
[[0.47499974 0.52417068]]
y: [0, 1]
[[0.48299912 0.52484163]]
y: [1, 0]
[[0.5028727  0.49326639]]
y: [1, 0]
[[0.51834613 0.49446922]]
y: [1, 0]
[[0.51711118 0.49151054]]
y: [0, 1]
[[0.47472389 0.52833322]]
y: [1, 0]
[[0.49361818 0.50248623]]
y: [1, 0]
[[0.47453682 0.52727131]]
y: [1, 0]
[[0.47605786 0.5453106 ]]
y: [1, 0]
[[0.50192946 0.51279947]]
y: [0, 1]
[[0.50459893 0.50112757]]
y: [1, 0]
[[0.50607012 0.49225666]]
y: [1, 0]
[[0.5001891  0.49843087]]
y: [0, 1]
[[0.48062802 0.51640323]]
y: [1, 0]
[[0.49003535 0.52848978]]
y: [0, 1]
[[0.49025955 0.54859561]]
y:

[[0.49641024 0.53343672]]
y: [1, 0]
[[0.50304016 0.49559941]]
y: [0, 1]
[[0.46748993 0.52882034]]
y: [0, 1]
[[0.46987669 0.51026845]]
y: [1, 0]
[[0.50687878 0.49432742]]
y: [1, 0]
[[0.49506216 0.50588802]]
y: [0, 1]
[[0.47656481 0.53000579]]
y: [1, 0]
[[0.46603412 0.52846616]]
y: [0, 1]
[[0.47683468 0.53022049]]
y: [1, 0]
[[0.49684319 0.49637862]]
y: [1, 0]
[[0.50677953 0.51265041]]
y: [1, 0]
[[0.50175298 0.50390161]]
y: [1, 0]
[[0.49846622 0.53331037]]
y: [1, 0]
[[0.50302363 0.49581857]]
y: [0, 1]
[[0.48395747 0.51273428]]
y: [0, 1]
[[0.48342026 0.52571856]]
y: [1, 0]
[[0.46481298 0.52198168]]
y: [1, 0]
[[0.47265096 0.52377965]]
y: [1, 0]
[[0.50150694 0.48485659]]
y: [0, 1]
[[0.49581332 0.4952156 ]]
y: [0, 1]
[[0.46973254 0.526102  ]]
y: [0, 1]
[[0.46305165 0.53220288]]
y: [0, 1]
[[0.48853272 0.52598155]]
y: [1, 0]
[[0.46252695 0.52335263]]
y: [0, 1]
[[0.46662741 0.53445861]]
y: [1, 0]
[[0.49377836 0.48044351]]
y: [1, 0]
[[0.48427831 0.49048897]]
y: [1, 0]
[[0.50464971 0.49497005]]
y:

y: [1, 0]
[[0.50176106 0.48404807]]
y: [0, 1]
[[0.49614902 0.49450667]]
y: [0, 1]
[[0.46930781 0.52569706]]
y: [0, 1]
[[0.46254386 0.53185239]]
y: [0, 1]
[[0.4880544  0.52570731]]
y: [1, 0]
[[0.46213337 0.52301769]]
y: [0, 1]
[[0.4660497  0.53420306]]
y: [1, 0]
[[0.49415095 0.47984675]]
y: [1, 0]
[[0.48440733 0.48991183]]
y: [1, 0]
[[0.50472187 0.49479043]]
y: [0, 1]
[[0.52496864 0.46539894]]
y: [1, 0]
[[0.50207291 0.495855  ]]
y: [1, 0]
[[0.48665409 0.49952303]]
y: [1, 0]
[[0.48983872 0.52190539]]
y: [1, 0]
[[0.49052914 0.51888983]]
y: [0, 1]
[[0.51098973 0.54201352]]
y: [1, 0]
[[0.47409809 0.51567932]]
y: [1, 0]
[[0.5134304 0.4968089]]
y: [1, 0]
[[0.50207803 0.49641922]]
y: [1, 0]
[[0.48592847 0.51495771]]
y: [0, 1]
[[0.53227426 0.53114649]]
y: [0, 1]
[[0.4866379  0.52701947]]
y: [1, 0]
[[0.4992686  0.49966747]]
y: [0, 1]
[[0.48191706 0.54120056]]
y: [1, 0]
[[0.47671706 0.52805248]]
y: [1, 0]
[[0.49853772 0.51060932]]
y: [1, 0]
[[0.48969614 0.49352326]]
y: [1, 0]
[[0.46406599 0.53147

y: [1, 0]
[[0.48081941 0.50266007]]
y: [0, 1]
[[0.51474056 0.49305472]]
y: [1, 0]
[[0.50383243 0.49378354]]
y: [1, 0]
[[0.50191278 0.49579084]]
y: [1, 0]
[[0.49436097 0.49194453]]
y: [1, 0]
[[0.50999413 0.49632433]]
y: [1, 0]
[[0.49964417 0.49078791]]
y: [0, 1]
[[0.47809225 0.50529581]]
y: [0, 1]
[[0.48391853 0.50488861]]
y: [1, 0]
[[0.47397489 0.51595801]]
y: [1, 0]
[[0.48331185 0.51821528]]
y: [1, 0]
[[0.51708047 0.49629534]]
y: [1, 0]
[[0.50621755 0.50752381]]
y: [1, 0]
[[0.4787817  0.53170225]]
y: [1, 0]
[[0.49487603 0.49191282]]
y: [1, 0]
[[0.5035293  0.49702514]]
y: [0, 1]
[[0.4725241  0.52713579]]
y: [0, 1]
[[0.50365753 0.50953138]]
y: [0, 1]
[[0.5025465  0.50054259]]
y: [1, 0]
[[0.49803475 0.49150708]]
y: [1, 0]
[[0.5001368  0.49564095]]
y: [1, 0]
[[0.50231943 0.49531109]]
y: [1, 0]
[[0.46069637 0.5245039 ]]
y: [1, 0]
[[0.49803397 0.50730783]]
y: [0, 1]
[[0.47964039 0.52065335]]
y: [1, 0]
[[0.49503168 0.51032372]]
y: [1, 0]
[[0.49840903 0.4953006 ]]
y: [1, 0]
[[0.45081014 0.528

y: [1, 0]
[[0.46375054 0.52100378]]
y: [1, 0]
[[0.47168018 0.52236728]]
y: [1, 0]
[[0.50258901 0.4822196 ]]
y: [0, 1]
[[0.49711796 0.49286577]]
y: [0, 1]
[[0.46851832 0.5249429 ]]
y: [0, 1]
[[0.46155482 0.5312407 ]]
y: [0, 1]
[[0.48710319 0.52525216]]
y: [1, 0]
[[0.46138881 0.5224073 ]]
y: [0, 1]
[[0.46487683 0.53381876]]
y: [1, 0]
[[0.49516314 0.47843788]]
y: [1, 0]
[[0.48488294 0.48861959]]
y: [1, 0]
[[0.50493901 0.49437775]]
y: [0, 1]
[[0.52646496 0.46350406]]
y: [1, 0]
[[0.50223783 0.49568438]]
y: [1, 0]
[[0.48693532 0.49848252]]
y: [1, 0]
[[0.48978894 0.52148252]]
y: [1, 0]
[[0.4900694 0.5188991]]
y: [0, 1]
[[0.5100392 0.5419511]]
y: [1, 0]
[[0.47372417 0.51543286]]
y: [1, 0]
[[0.51364086 0.49592195]]
y: [1, 0]
[[0.50256771 0.4957633 ]]
y: [1, 0]
[[0.48518042 0.51500262]]
y: [0, 1]
[[0.53105419 0.53150348]]
y: [0, 1]
[[0.48585347 0.5272063 ]]
y: [1, 0]
[[0.49928421 0.49928551]]
y: [0, 1]
[[0.48061301 0.54109886]]
y: [1, 0]
[[0.47591553 0.52723231]]
y: [1, 0]
[[0.49845751 0.5101036

[[0.47270714 0.5268287 ]]
y: [1, 0]
[[0.49320681 0.50182145]]
y: [1, 0]
[[0.47284325 0.52544637]]
y: [1, 0]
[[0.47357692 0.54497544]]
y: [1, 0]
[[0.50116557 0.51251506]]
y: [0, 1]
[[0.50502688 0.49952123]]
y: [1, 0]
[[0.50683866 0.49123407]]
y: [1, 0]
[[0.50044254 0.49769167]]
y: [0, 1]
[[0.47884946 0.51542277]]
y: [1, 0]
[[0.48856115 0.52656589]]
y: [0, 1]
[[0.48699397 0.54904879]]
y: [0, 1]
[[0.44200216 0.54238888]]
y: [1, 0]
[[0.47923079 0.51989974]]
y: [1, 0]
[[0.50417374 0.49640449]]
y: [0, 1]
[[0.47973541 0.52334748]]
y: [1, 0]
[[0.47465589 0.52616519]]
y: [0, 1]
[[0.47373031 0.52249239]]
y: [1, 0]
[[0.45692759 0.55689082]]
y: [1, 0]
[[0.5049907  0.48944739]]
y: [1, 0]
[[0.48082012 0.5021793 ]]
y: [0, 1]
[[0.51510639 0.49251104]]
y: [1, 0]
[[0.50406174 0.49351221]]
y: [1, 0]
[[0.50204446 0.4956561 ]]
y: [1, 0]
[[0.49472127 0.49152873]]
y: [1, 0]
[[0.51026441 0.49591165]]
y: [1, 0]
[[0.49998057 0.49031133]]
y: [0, 1]
[[0.47807828 0.50486615]]
y: [0, 1]
[[0.48394331 0.50430397]]
y:

y: [0, 1]
[[0.46566114 0.52751035]]
y: [0, 1]
[[0.46963338 0.5081733 ]]
y: [1, 0]
[[0.50762801 0.49316245]]
y: [1, 0]
[[0.49516536 0.5053988 ]]
y: [0, 1]
[[0.4749411  0.52832223]]
y: [1, 0]
[[0.46396158 0.5275981 ]]
y: [0, 1]
[[0.47515875 0.52861091]]
y: [1, 0]
[[0.49729182 0.49535734]]
y: [1, 0]
[[0.50669765 0.51175179]]
y: [1, 0]
[[0.50170887 0.50339747]]
y: [1, 0]
[[0.49733446 0.5316218 ]]
y: [1, 0]
[[0.50335624 0.49546424]]
y: [0, 1]
[[0.4825029  0.51212733]]
y: [0, 1]
[[0.48174633 0.52464416]]
y: [1, 0]
[[0.46345526 0.52073538]]
y: [1, 0]
[[0.47145353 0.52194229]]
y: [1, 0]
[[0.50318454 0.48122279]]
y: [0, 1]
[[0.49776567 0.4919497 ]]
y: [0, 1]
[[0.46818548 0.52462351]]
y: [0, 1]
[[0.46110654 0.53100998]]
y: [0, 1]
[[0.48665905 0.52509779]]
y: [1, 0]
[[0.46106594 0.522158  ]]
y: [0, 1]
[[0.46431366 0.53371924]]
y: [1, 0]
[[0.49581166 0.47763592]]
y: [1, 0]
[[0.48524702 0.48792233]]
y: [1, 0]
[[0.50508814 0.49414902]]
y: [0, 1]
[[0.52740573 0.46241606]]
y: [1, 0]
[[0.50233725 0.495

y: [1, 0]
[[0.50548254 0.48883358]]
y: [1, 0]
[[0.48089556 0.50177023]]
y: [0, 1]
[[0.51550079 0.49199747]]
y: [1, 0]
[[0.5042985  0.49324904]]
y: [1, 0]
[[0.50217652 0.49552188]]
y: [1, 0]
[[0.49509279 0.49112526]]
y: [1, 0]
[[0.51055676 0.49552179]]
y: [1, 0]
[[0.5003416  0.48986057]]
y: [0, 1]
[[0.47813445 0.50450397]]
y: [0, 1]
[[0.4840555  0.50380404]]
y: [1, 0]
[[0.47380187 0.51474183]]
y: [1, 0]
[[0.48252575 0.51731126]]
y: [1, 0]
[[0.51751219 0.49503564]]
y: [1, 0]
[[0.50644984 0.50679437]]
y: [1, 0]
[[0.47757987 0.53164497]]
y: [1, 0]
[[0.49545401 0.49112306]]
y: [1, 0]
[[0.50379221 0.49667626]]
y: [0, 1]
[[0.47126765 0.52662253]]
y: [0, 1]
[[0.50394271 0.50855874]]
y: [0, 1]
[[0.50265537 0.50034866]]
y: [1, 0]
[[0.49875054 0.49061368]]
y: [1, 0]
[[0.50047414 0.49527822]]
y: [1, 0]
[[0.50275715 0.49474405]]
y: [1, 0]
[[0.45962636 0.52432085]]
y: [1, 0]
[[0.49814489 0.50696049]]
y: [0, 1]
[[0.47910876 0.51937502]]
y: [1, 0]
[[0.49428637 0.51001675]]
y: [1, 0]
[[0.49877916 0.494

y: [1, 0]
[[0.50657317 0.50655598]]
y: [1, 0]
[[0.47721908 0.53170504]]
y: [1, 0]
[[0.49568945 0.49084625]]
y: [1, 0]
[[0.50389708 0.49655162]]
y: [0, 1]
[[0.47092785 0.52655217]]
y: [0, 1]
[[0.50410037 0.5082433 ]]
y: [0, 1]
[[0.50270195 0.50028121]]
y: [1, 0]
[[0.4990351  0.49029603]]
y: [1, 0]
[[0.50060299 0.49514482]]
y: [1, 0]
[[0.50293195 0.49454252]]
y: [1, 0]
[[0.45931801 0.52433713]]
y: [1, 0]
[[0.49820323 0.50684578]]
y: [0, 1]
[[0.47904686 0.51902678]]
y: [1, 0]
[[0.49408541 0.50997517]]
y: [1, 0]
[[0.49892888 0.49462175]]
y: [1, 0]
[[0.44918082 0.52867882]]
y: [1, 0]
[[0.50173611 0.4944397 ]]
y: [0, 1]
[[0.49357778 0.49447747]]
y: [0, 1]
[[0.49593356 0.52219968]]
y: [0, 1]
[[0.5017687  0.53801254]]
y: [1, 0]
[[0.50747096 0.49825673]]
y: [1, 0]
[[0.50281802 0.49512268]]
y: [0, 1]
[[0.47780031 0.52349031]]
y: [1, 0]
[[0.50177451 0.48944152]]
y: [0, 1]
[[0.48627697 0.51287827]]
y: [1, 0]
[[0.462583  0.5219691]]
y: [0, 1]
[[0.48655008 0.52595426]]
y: [1, 0]
[[0.50184341 0.49018

y: [1, 0]
[[0.50081627 0.48932273]]
y: [0, 1]
[[0.47827269 0.50411694]]
y: [0, 1]
[[0.48428037 0.50326178]]
y: [1, 0]
[[0.47389359 0.51417432]]
y: [1, 0]
[[0.48227161 0.51697013]]
y: [1, 0]
[[0.51790051 0.49436687]]
y: [1, 0]
[[0.50666279 0.5064043 ]]
y: [1, 0]
[[0.47699722 0.53176169]]
y: [1, 0]
[[0.49585018 0.49066577]]
y: [1, 0]
[[0.50396828 0.49646982]]
y: [0, 1]
[[0.47072845 0.52653023]]
y: [0, 1]
[[0.50421584 0.50804321]]
y: [0, 1]
[[0.50273419 0.50023731]]
y: [1, 0]
[[0.49922801 0.49008793]]
y: [1, 0]
[[0.50068935 0.49505645]]
y: [1, 0]
[[0.50305063 0.4944105 ]]
y: [1, 0]
[[0.45913171 0.52436526]]
y: [1, 0]
[[0.49824559 0.50677249]]
y: [0, 1]
[[0.47903381 0.51882161]]
y: [1, 0]
[[0.49396764 0.50996251]]
y: [1, 0]
[[0.4990309  0.49450595]]
y: [1, 0]
[[0.44896534 0.52869957]]
y: [1, 0]
[[0.50183525 0.49432402]]
y: [0, 1]
[[0.49370293 0.49432274]]
y: [0, 1]
[[0.49567368 0.52228447]]
y: [0, 1]
[[0.50132623 0.53831406]]
y: [1, 0]
[[0.50751399 0.49820276]]
Predicted Values are:
length

In [ ]:
data

Age  Experience    Income    Family     CCAvg  Education  Mortgage  \
447  0.319455    0.252503 -0.060271 -1.216855 -0.307836   1.332484 -0.555524   
70  -0.291258   -0.183538  0.895646 -1.216855  0.893892  -1.049078 -0.555524   
441  0.581189    0.601336 -0.668581 -1.216855 -0.365061   0.141703 -0.555524   
340  1.191902    1.211793  0.374237 -1.216855  0.378866  -1.049078 -0.555524   
387 -1.250949   -1.317246  0.178709  1.397414 -0.078935   0.141703 -0.555524   
..        ...         ...       ...       ...       ...        ...       ...   
95  -0.640236   -0.706788 -0.559954  1.397414 -0.994537   1.332484 -0.555524   
391  1.104657    1.037377 -1.407244  0.525991 -0.937312   1.332484 -0.555524   
251  0.755678    0.688544  2.090542 -0.345432  2.438970   0.141703  2.640036   
401 -1.425438   -1.578870 -0.951011  1.397414 -0.250611   0.141703  0.545715   
465  1.802614    1.909459 -0.842384 -1.216855 -0.021710   0.141703  1.135664   

     Personal Loan  Securities Account  CD Account    Online CreditCard  
447      -0.325875           -0.341423    -0.25354 -1.216618     [1, 0]  
70       -0.325875           -0.341423    -0.25354 -1.216618     [0, 1]  
441      -0.325875            2.928915    -0.25354  0.821951     [1, 0]  
340      -0.325875           -0.341423    -0.25354  0.821951     [0, 1]  
387      -0.325875           -0.341423    -0.25354  0.821951     [1, 0]  
..             ...                 ...         ...       ...        ...  
95       -0.325875           -0.341423    -0.25354  0.821951     [1, 0]  
391      -0.325875           -0.341423    -0.25354 -1.216618     [0, 1]  
251       3.068659           -0.341423    -0.25354  0.821951     [1, 0]  
401      -0.325875           -0.341423    -0.25354 -1.216618     [0, 1]  
465      -0.325875           -0.341423    -0.25354  0.821951     [1, 0]  

[500 rows x 12 columns]

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Create a dataset as a NumPy array (example data)

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the data and transform the data
X = scaler.fit_transform(X)

# 'scaled_data' contains the standardized dataset
print("Original Data:\n", X)
print("Standardized Data:\n", scaled_data)


Original Data:
 [[-0.7346066  -0.710307   -1.30848164 ... -0.32084447 -0.20412415
   0.81649658]
 [-0.01204273 -0.07556457 -0.21186362 ... -0.32084447 -0.20412415
  -1.22474487]
 [ 0.89116211  0.83121031 -0.41328326 ... -0.32084447 -0.20412415
   0.81649658]
 ...
 [-0.37332467 -0.34759704 -0.45804318 ... -0.32084447 -0.20412415
   0.81649658]
 [-1.09588854 -1.07301695 -0.25662354 ... -0.32084447 -0.20412415
  -1.22474487]
 [-1.18620902 -1.07301695 -0.54756301 ... -0.32084447 -0.20412415
   0.81649658]]
Standardized Data:
 [[-0.7346066  -0.710307   -1.30848164 ... -0.32084447 -0.20412415
   0.81649658]
 [-0.01204273 -0.07556457 -0.21186362 ... -0.32084447 -0.20412415
  -1.22474487]
 [ 0.89116211  0.83121031 -0.41328326 ... -0.32084447 -0.20412415
   0.81649658]
 ...
 [-0.37332467 -0.34759704 -0.45804318 ... -0.32084447 -0.20412415
   0.81649658]
 [-1.09588854 -1.07301695 -0.25662354 ... -0.32084447 -0.20412415
  -1.22474487]
 [-1.18620902 -1.07301695 -0.54756301 ... -0.32084447 -0.20412

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
lst=402
print(sigmoid(lst))

1.0


In [ ]:
Y_test

379    [0, 0, 0, 1, 0, 0]
288    [0, 0, 0, 1, 0, 0]
232    [0, 0, 0, 0, 1, 0]
289    [0, 0, 0, 0, 1, 0]
347    [0, 0, 0, 0, 0, 1]
              ...        
287    [0, 0, 1, 0, 0, 0]
205    [0, 0, 0, 0, 1, 0]
371    [0, 0, 0, 0, 0, 1]
27     [0, 0, 0, 0, 1, 0]
190    [0, 0, 0, 1, 0, 0]
Name: Index, Length: 80, dtype: object

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(actual,predicted)*100
    print(f"Accuracy: {accuracy * 100:.2f}%")

In [ ]:
X_train

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
3837  3838   44          19      40     92350       4   0.00          2   
4960  4961   58          28      81     91604       1   3.00          3   
968    969   55          31      90     92868       1   2.70          2   
3238  3239   52          28      49     94928       4   1.10          2   
3698  3699   38          12      59     96001       3   0.50          3   
...    ...  ...         ...     ...       ...     ...    ...        ...   
1518  1519   43          17      64     95053       4   3.00          3   
179    180   62          37      11     91942       1   0.10          1   
1877  1878   51          24      78     90037       1   2.67          2   
3572  3573   30           6      30     90245       1   0.40          3   
3704  3705   36          11     184     91304       2   5.10          2   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  
3837         0              0                   0           0       1  
4960         0              0                   0           0       1  
968          0              0                   0           0       1  
3238         0              0                   0           0       1  
3698         0              0                   1           1       1  
...        ...            ...                 ...         ...     ...  
1518       221              1                   0           0       1  
179          0              0                   0           0       1  
1877         0              0                   0           0       1  
3572         0              0                   0           0       1  
3704         0              1                   0           0       0  

[120 rows x 13 columns]

In [ ]:
int(len(data)*0.8)


120

In [ ]:
X_test

Height  Weight
193     155      71
17      165     155
16      142     159
127     166     153
60      150      70
..      ...     ...
356     159     140
334     163     110
162     142     131
84      183      79
174     187      92

[80 rows x 2 columns]

In [ ]:
f=X.iloc[0,:]

In [ ]:
xa=f.to_numpy()

In [ ]:
b=np.array([1,1,1,1,1,1,1,1,1,1,1])

In [ ]:
np.dot(xa,b.T)

112.5

In [ ]:
def sigmoid(x):
    return 1 / (1 + math.exp(-x))
res=sigmoid([0.755,0.66])

TypeError: bad operand type for unary -: 'list'

In [ ]:
Xtrain=Xtrain.to_numpy()

In [ ]:
Xtrain[0].reshape(Xtrain[0].shape[0],1)

array([[46. ],
       [21. ],
       [41. ],
       [ 1. ],
       [ 0.5],
       [ 3. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ],
       [ 0. ]])

In [ ]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_array = original_array.reshape(2, 3)

# Print the reshaped array
print(reshaped_array)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix with the second dimension inferred
reshaped_array = original_array.reshape(2, -1)

# The '-1' automatically calculates the required number of columns
print(reshaped_array)


[[1 2 3]
 [4 5 6]]


In [ ]:
Xtrain[0].shape

KeyError: 0

In [ ]:
Xtrain.iloc[0].shape[0]

11

In [ ]:
Xtrain.iloc[0].reshape(Xtrain.iloc[p].shape[0],1)

AttributeError: 'Series' object has no attribute 'reshape'

In [ ]:
Xtrain[0]

array([46. , 21. , 41. ,  1. ,  0.5,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ])

In [ ]:
np.matmul(xa,b.T)

112.5

In [ ]:
a=Xtrain[0]

In [ ]:
for i in  range(len(a)):
    a[i]=a[i]*0.5
    print(a[i])

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
output_array = 1 / (1 + np.exp(-xtrain))

In [ ]:
output_array

array([[0.50516956],
       [0.68819415],
       [0.55457863],
       [0.58856819],
       [0.72016848]])

In [ ]:
xtrain=np.array([[0.02067898],
       [0.79169028],
       [0.21918787],
       [0.3580495],
       [0.94529749]])

In [ ]:
xtrain=np.array([59.72447983 87.08031397 63.04703111 46.85336364 83.04705158])

SyntaxError: invalid syntax (<ipython-input-158-1094227526a7>, line 1)

In [ ]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

# Perform matrix multiplication using matmul
matrix = np.matmul(matrix1, matrix2)

# Print the result
print(matrix)


[[ 58  64]
 [139 154]]


In [ ]:
af = matrix.flatten()

In [ ]:
af

array([ 58,  64, 139, 154])

In [ ]:
import numpy as np

# Define two matrices
matrix1 = np.array([1. 1. 1.])

matrix2 = np.array([0.10022536])

# Perform matrix multiplication using matmul
result_matrix = np.matmul(matrix1, matrix2)
print(result_matrix)
res1=list(result_matrix)
print(res1)

# Convert the result to an array
result_array = np.array(result_matrix)
result=result_array.flatten()
res=np.array(result)

# Print the result as an array
print(list(res))


SyntaxError: invalid syntax (<ipython-input-269-f211625b7acf>, line 4)

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
sigmoid(np.array(res))

array([1., 1., 1., 1.])

In [ ]:
import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # Initialize network architecture and random weights
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        # Initialize weights and biases for the hidden layer
        self.weights_hidden = np.random.randn(self.input_size, self.hidden_size)
        self.bias_hidden = np.zeros((1, self.hidden_size))

        # Initialize weights and biases for the output layer
        self.weights_output = np.random.randn(self.hidden_size, self.output_size)
        self.bias_output = np.zeros((1, self.output_size))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def feedforward(self, x):
        # Calculate the hidden layer output
        self.hidden_layer_input = np.dot(x, self.weights_hidden) + self.bias_hidden
        self.hidden_layer_output = self.sigmoid(self.hidden_layer_input)

        # Calculate the output layer output
        self.output_layer_input = np.dot(self.hidden_layer_output, self.weights_output) + self.bias_output
        self.output_layer_output = self.sigmoid(self.output_layer_input)
        print(self.output_layer_output )

        return self.output_layer_output

    def backward(self, x, y, output):
        # Backpropagation
        print(x)
        print(y)
        error_output = y - output
        delta_output = error_output * self.sigmoid_derivative(output)

        error_hidden = delta_output.dot(self.weights_output.T)
        delta_hidden = error_hidden * self.sigmoid_derivative(self.hidden_layer_output)

        # Update weights and biases
        self.weights_output += self.hidden_layer_output.T.dot(delta_output)
        self.bias_output += np.sum(delta_output, axis=0, keepdims=True)

        self.weights_hidden += x.T.dot(delta_hidden)
        self.bias_hidden += np.sum(delta_hidden, axis=0, keepdims=True)

    def train(self, x, y, epochs):
        for _ in range(epochs):
            output = self.feedforward(x)
            self.backward(x, y, output)

if __name__ == "__main__":
    # Sample dataset (XOR problem)


    # Create and train the MLP
    mlp = NeuralNetwork(input_size=2, hidden_size=4, output_size=1)
    mlp.train(x[0], Y[0], epochs=10000)

    # Test the trained model
    for x in X:
        result = mlp.feedforward(x)
        print(f"Input: {x}, Predicted Output: {result}")


[[0.93331288]]
[1.00508779 0.49316616]
[0, 0, 0, 0, 1, 0]


ValueError: shapes (1,6) and (1,4) not aligned: 6 (dim 1) != 1 (dim 0)

In [ ]:
 x=X.to_numpy()
x[0]

array([1.00508779, 0.49316616])

In [ ]:
wt=np.random.rand(3,4)
           # np.ones((self.L[i+1], 1))
#lt=np.array([1,1,1,1])
#s=np.stack([wt,lt])
#print(s)

In [ ]:
na=np.ndarray([[1,1,1,1]])

TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
wt

array([[0.1932794 , 0.49498504, 0.06213345, 0.45921207],
       [0.56805429, 0.52017749, 0.77305298, 0.03582849],
       [0.79952212, 0.98170391, 0.09194809, 0.54800016]])

In [ ]:
a=

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
a

array([0.89085275, 0.72107261, 0.6984327 , 0.13711821, 0.5718006 ,
       0.05040762, 0.62624504, 0.03692883, 0.82624762, 0.50601635,
       0.2065967 , 0.45880366, 1.        , 1.        , 1.        ])

In [ ]:
wt

array([[0.89085275, 0.72107261, 0.6984327 , 0.13711821],
       [0.5718006 , 0.05040762, 0.62624504, 0.03692883],
       [0.82624762, 0.50601635, 0.2065967 , 0.45880366]])

In [ ]:
a.reshape(3)

ValueError: cannot reshape array of size 15 into shape (3,)

In [ ]:
BIAS_hidden = np.array([1 for i in range(5)])

In [ ]:
BIAS_hidden

array([1, 1, 1, 1, 1])

In [ ]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]
print(y)

2547    [1, 0]
4028    [1, 0]
259     [1, 0]
266     [1, 0]
756     [1, 0]
         ...  
4087    [1, 0]
2124    [1, 0]
2474    [1, 0]
4250    [0, 1]
3874    [1, 0]
Name: CreditCard, Length: 5000, dtype: object


In [ ]:
import numpy as np

# Define the architecture
input_size = 11
hidden_layer_sizes = [5, 5, 5, 5, 5]
output_size = 2

# Initialize weights and biases
def initialize_weights_and_biases(layer_sizes):
    weights = [np.random.randn(layer_sizes[i], layer_sizes[i+1]) for i in range(len(layer_sizes) - 1)]
    biases = [np.zeros((1, layer_sizes[i+1])) for i in range(len(layer_sizes) - 1)]
    return weights, biases

# Define the activation function (e.g., sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Forward propagation
def forward_propagation(X, weights, biases):
    activations = [X]
    for i in range(len(weights)):
        z = np.dot(activations[-1], weights[i]) + biases[i]
        a = sigmoid(z)
        activations.append(a)
    return activations

# Compute the derivative of the activation function
def sigmoid_derivative(x):
    return x * (1 - x)

# Backpropagation to update weights and biases
def backpropagation(X, Y, weights, biases, activations, learning_rate):
    num_layers = len(weights)
    delta = [None] * num_layers
    delta[-1] = (activations[-1] - Y)  # Calculate the error in the output layer

    for i in range(num_layers - 2, -1, -1):
        delta[i] = delta[i + 1].dot(weights[i + 1].T) * sigmoid_derivative(activations[i + 1])

    for i in range(num_layers):
        weights[i] -= learning_rate * activations[i].T.dot(delta[i])
        biases[i] -= learning_rate * np.sum(delta[i], axis=0, keepdims=True)

# Sample input and output data
X = x
Y = y

# Initialize weights and biases
weights, biases = initialize_weights_and_biases([input_size] + hidden_layer_sizes + [output_size])

# Learning rate
learning_rate = 0.01

# Training loop (you would typically use a dataset and multiple iterations)
for _ in range(1000):
    activations = forward_propagation(X, weights, biases)
    backpropagation(X, Y, weights, biases, activations, learning_rate)

# The last element of 'activations' contains the output of the MLP
output = activations[-1]

print("Input data:", X)
print("MLP output:", output)


ValueError: operands could not be broadcast together with shapes (5000,2) (5000,) 